import { 
  User, 
  CampusEvent, 
  CampusVenue, 
  Registration, 
  AttendanceRecord, 
  Certificate, 
  CampusNotification, 
  EventFeedback,
  AchievementBadge
} from '../types';

export const INITIAL_USERS: User[] = [
  {
    _id: 'student-amit-y25170504',
    name: 'Amit Sharma',
    email: 'y25170504@dhsgsu.edu.in',
    passwordHash: 'Programmer@01',
    rollNumber: 'Y25170504',
    department: 'Department of Computer Science & Applications (DCSA)',
    semester: 2,
    role: 'student',
    organizerStatus: 'NONE',
    interests: ['Technology', 'Coding', 'Entrepreneurship', 'Workshop'],
    profileImage: '',
    bio: 'Undergraduate Computer Science student at Dr. Harisingh Gour Vishwavidyalaya, Sagar.',
    preferredLanguage: 'en',
    phone: '+91 98260 12345',
    createdAt: '2026-09-30T10:00:00Z',
    updatedAt: '2026-09-30T10:00:00Z',
  },
  {
    _id: 'student-1',
    name: 'Amit Sharma',
    email: 'amit.sharma@dhsgsu.edu.in',
    rollNumber: 'Y23141042',
    department: 'Department of Computer Science & Applications',
    semester: 6,
    role: 'student',
    organizerStatus: 'NONE',
    interests: ['Technology', 'Coding', 'Entrepreneurship', 'Workshop'],
    profileImage: '',
    bio: 'Final year computing student interested in distributed systems and campus hackathons.',
    preferredLanguage: 'en',
    phone: '+91 98260 12345',
    createdAt: '2025-08-01T09:00:00Z',
    updatedAt: '2026-03-15T11:20:00Z',
  },
  {
    _id: 'student-2',
    name: 'Priya Patel',
    email: 'priya.patel@dhsgsu.edu.in',
    rollNumber: 'Y23122018',
    department: 'Department of Electronics & Communication',
    semester: 4,
    role: 'organizer',
    organizerStatus: 'PENDING',
    designation: 'B.Tech Student & Electronics Society Secretary',
    organization: 'DHSGSU Electronics Society',
    interests: ['Cultural', 'Sports', 'Seminar', 'Workshop'],
    profileImage: '',
    phone: '+91 98260 67890',
    createdAt: '2025-08-10T10:00:00Z',
    updatedAt: '2026-02-18T14:10:00Z',
  },
  {
    _id: 'student-3',
    name: 'Rohan Mehra',
    email: 'rohan.mehra@dhsgsu.edu.in',
    rollNumber: 'Y23141088',
    department: 'Department of Computer Science & Applications',
    semester: 6,
    role: 'organizer',
    organizerStatus: 'REJECTED',
    designation: 'M.Sc Student & Open Source Club Lead',
    organization: 'DHSGSU Open Source Initiative',
    interests: ['Coding', 'Competition', 'Technology'],
    profileImage: '',
    phone: '+91 94250 11223',
    createdAt: '2025-08-05T09:00:00Z',
    updatedAt: '2026-02-20T10:00:00Z',
  },
  {
    _id: 'org-1',
    name: 'Dr. Alok Sahay',
    email: 'alok.sahay@dhsgsu.edu.in',
    rollNumber: 'EMP-DCSA-104',
    department: 'Department of Computer Science & Applications (DCSA)',
    role: 'organizer',
    organizerStatus: 'VERIFIED',
    designation: 'Associate Professor & Faculty Convener',
    organization: 'DHSGSU Centre for Computing & Innovation',
    interests: ['Technology', 'Coding', 'Workshop', 'Seminar'],
    profileImage: '',
    phone: '+91 75822 64201',
    createdAt: '2024-06-01T09:00:00Z',
    updatedAt: '2026-01-10T09:00:00Z',
  },
  {
    _id: 'org-2',
    name: 'Prof. R.K. Trivedi',
    email: 'rk.trivedi@dhsgsu.edu.in',
    rollNumber: 'EMP-FET-201',
    department: 'Department of Technology & Engineering',
    role: 'organizer',
    organizerStatus: 'VERIFIED',
    designation: 'Professor & Dean, Faculty of Engineering & Technology',
    organization: 'DHSGSU Robotics & Automation Council',
    interests: ['Competition', 'Workshop', 'Sports'],
    profileImage: '',
    phone: '+91 75822 64205',
    createdAt: '2024-07-15T09:00:00Z',
    updatedAt: '2026-02-12T10:00:00Z',
  },
  {
    _id: 'admin-1',
    name: 'Prof. S.P. Gautam',
    email: 'dsw@dhsgsu.edu.in',
    rollNumber: 'ADMIN-DSW-001',
    department: "Office of the Dean of Students' Welfare (DSW)",
    role: 'admin',
    organizerStatus: 'VERIFIED',
    designation: "Dean of Students' Welfare & Proctor",
    organization: 'Dr. Harisingh Gour Vishwavidyalaya, Sagar (M.P.)',
    interests: ['Academic', 'Administration', 'Governance'],
    profileImage: '',
    phone: '+91 75822 64400',
    createdAt: '2023-01-01T09:00:00Z',
    updatedAt: '2026-01-01T09:00:00Z',
  }
];

export const INITIAL_ORGANIZER_REQUESTS: import('../types').OrganizerVerificationRequest[] = [
  {
    id: 'req-01',
    userId: 'student-2',
    fullName: 'Priya Patel',
    universityId: 'Y23122018',
    department: 'Department of Electronics & Communication',
    designation: 'B.Tech Student & Electronics Society Secretary',
    email: 'priya.patel@dhsgsu.edu.in',
    phone: '+91 98260 67890',
    reason: 'Requesting permission to organize the Annual VLSI & Embedded Systems Workshop for undergraduate engineering students in Raman Theatre.',
    status: 'PENDING',
    submittedAt: '2026-09-28T14:30:00Z',
  },
  {
    id: 'req-02',
    userId: 'student-3',
    fullName: 'Rohan Mehra',
    universityId: 'Y23141088',
    department: 'Department of Computer Science & Applications',
    designation: 'M.Sc Student & Open Source Club Lead',
    email: 'rohan.mehra@dhsgsu.edu.in',
    phone: '+91 94250 11223',
    reason: 'Organizing an independent late-night gaming tournament in the computing lab without faculty faculty advisor endorsement.',
    status: 'REJECTED',
    submittedAt: '2026-09-25T10:15:00Z',
    reviewedAt: '2026-09-26T16:20:00Z',
    reviewRemarks: 'Requires formal endorsement letter from Head of Department (DCSA) and a designated faculty convener.',
  },
  {
    id: 'req-03',
    userId: 'org-1',
    fullName: 'Dr. Alok Sahay',
    universityId: 'EMP-DCSA-104',
    department: 'Department of Computer Science & Applications (DCSA)',
    designation: 'Associate Professor & Faculty Convener',
    email: 'alok.sahay@dhsgsu.edu.in',
    phone: '+91 75822 64201',
    reason: 'Faculty Convener for Departmental Seminars, ACM Student Chapter, and National Computing Studios.',
    status: 'APPROVED',
    submittedAt: '2025-06-01T09:00:00Z',
    reviewedAt: '2025-06-02T11:00:00Z',
    reviewRemarks: 'Verified faculty credentials by Dean of Students Welfare Office.',
  }
];

export const DHSGSU_CAMPUS_CENTER = {
  name: 'Dr. Harisingh Gour Vishwavidyalaya',
  address: 'University Road, Patharia Hills, Sagar, Madhya Pradesh 470003, India',
  latitude: 23.8268733,
  longitude: 78.7712647,
  defaultZoom: 16,
};

export const CAMPUS_VENUES: CampusVenue[] = [
  // ============================================================================
  // 1. GOOGLE MAPS + OFFICIAL DHSGSU VERIFIED CAMPUS LOCATIONS
  // Every entry below has an exact verified Google Maps Place & WGS84 coordinate
  // ============================================================================
  {
    id: 'venue-stadium',
    name: 'Abdul Gani Khan Stadium',
    secondaryName: 'Dr. Hari Singh Gour University Stadium',
    plusCode: 'RQF8+W96',
    category: 'Sports',
    latitude: 23.8247787,
    longitude: 78.7658891,
    description: 'University sports stadium and ground at Dr. Harisingh Gour Vishwavidyalaya.',
    address: 'RQF8+W96, Tili Road / Gopal Ganj, Dr. Harisingh Gour Vishwavidyalaya, Sagar, Madhya Pradesh 470001',
    verified: 'verified',
    source: 'Google Maps Place (RQF8+W96 Dr.Hari Singh Gour University Stadium / Abdul Gani Khan Stadium) + Official DHSGSU Sports Records',
    navigationQuery: 'Abdul Gani Khan Stadium, Dr. Harisingh Gour Vishwavidyalaya, Sagar, Madhya Pradesh',
    isEventVenue: true,
    building: 'Abdul Gani Khan Stadium',
  },
  {
    id: 'utd-gym',
    name: 'UTD Gym',
    plusCode: 'RQG7+4W7',
    category: 'Sports',
    latitude: 23.8252790,
    longitude: 78.7647850,
    description: 'University Teaching Department gymnasium facility adjacent to the university stadium.',
    address: 'RQG7+4W7, SH 15A, Dr. Harisingh Gour Central University, Sagar, Madhya Pradesh 470001',
    verified: 'verified',
    source: 'Google Maps Place (RQG7+4W7 UTD Gym, Dr. Harisingh Gour Central University)',
    navigationQuery: 'UTD Gym, Dr. Harisingh Gour Central University, Sagar',
    isEventVenue: false,
    building: 'UTD Gym',
  },
  {
    id: 'venue-central-library',
    name: 'Jawaharlal Nehru Central Library',
    plusCode: 'RQGC+QF6',
    category: 'Library',
    latitude: 23.8268733,
    longitude: 78.7712647,
    description: 'Central university library at Dr. Harisingh Gour Vishwavidyalaya.',
    address: 'RQGC+QF6, SH 15A, Dr. Harisingh Gour Central University, Sagar, Madhya Pradesh 470003',
    verified: 'verified',
    source: 'Google Maps Place (RQGC+QF6 Jawaharlal Nehru Central Library) + Official DHSGSU Library Portal',
    navigationQuery: 'Jawaharlal Nehru Central Library, Dr. Harisingh Gour Central University, Sagar',
    isEventVenue: true,
    building: 'Jawaharlal Nehru Central Library',
  },
  {
    id: 'venue-gour-bhavan',
    name: 'Administrative Building',
    secondaryName: 'Central University Administration & Gour Samiti Kaksh',
    plusCode: 'RQGC+9CX',
    category: 'Administration',
    latitude: 23.8259935,
    longitude: 78.7711182,
    description: 'Central administrative building at Dr. Harisingh Gour Vishwavidyalaya.',
    address: 'RQGC+9CX, SH 15A, Dr. Harisingh Gour Central University, Sagar, Madhya Pradesh 470003',
    verified: 'verified',
    source: 'Google Maps Place (RQGC+9CX Administrative Building, Dr. Harisingh Gour Central University)',
    navigationQuery: 'Administrative Building, Dr. Harisingh Gour Central University, Sagar',
    isEventVenue: true,
    building: 'Administrative Building',
  },
  {
    id: 'venue-abhimanch',
    name: 'Abhimanch Sabhagar',
    plusCode: 'RQFF+X2C',
    category: 'Event Venue',
    latitude: 23.8250284,
    longitude: 78.7720508,
    description: 'University auditorium and event hall at Dr. Harisingh Gour Vishwavidyalaya.',
    address: 'RQFF+X2C, Dr. Harisingh Gour Central University, Sagar, Madhya Pradesh 470003',
    verified: 'verified',
    source: 'Google Maps Place (RQFF+X2C Abhimanch Sabhagar, Dr. Harisingh Gour Central University)',
    navigationQuery: 'Abhimanch Sabhagar, Dr. Harisingh Gour Central University, Sagar',
    isEventVenue: true,
    building: 'Abhimanch Sabhagar',
  },
  {
    id: 'venue-dcsa-lab',
    name: 'Department of Computer Science and Applications',
    secondaryName: 'DCSA',
    plusCode: 'RQFJ+PP',
    category: 'Academic',
    latitude: 23.8241153,
    longitude: 78.7821585,
    description: 'Academic department of Computer Science and Applications at Dr. Harisingh Gour Vishwavidyalaya.',
    address: 'RQFJ+PP, Professors Colony, Patheriya Jat, Dr. Harisingh Gour Central University, Sagar, Madhya Pradesh 470003',
    verified: 'verified',
    source: 'Google Maps Place (RQFJ+PP Department of Computer Science and Applications) + Official DHSGSU Directory',
    navigationQuery: 'Department of Computer Science and Applications, Dr. Harisingh Gour University, Sagar',
    isEventVenue: true,
    building: 'Department of Computer Science and Applications',
  },
  {
    id: 'venue-geography-dept',
    name: 'Department of General and Applied Geography',
    plusCode: 'RQHC+6VH',
    category: 'Academic',
    latitude: 23.8280610,
    longitude: 78.7722260,
    description: 'Academic department of General and Applied Geography at Dr. Harisingh Gour Vishwavidyalaya.',
    address: 'RQHC+6VH, SH 15A, Dr. Harisingh Gour Central University, Sagar, Madhya Pradesh 470003',
    verified: 'verified',
    source: 'Google Maps Place (RQHC+6VH Department of General and Applied Geography) + Official DHSGSU Portal',
    navigationQuery: 'Department of General and Applied Geography, Dr. Harisingh Gour Central University, Sagar',
    isEventVenue: true,
    building: 'Department of General and Applied Geography',
  },
  {
    id: 'venue-law-hall',
    name: 'Department of Law',
    category: 'Academic',
    latitude: 23.8244929,
    longitude: 78.7700186,
    description: 'Academic department of Law at Dr. Harisingh Gour Vishwavidyalaya.',
    address: 'Dr. Harisingh Gour Central University, Sagar, Madhya Pradesh 470003',
    verified: 'verified',
    source: 'Google Maps Place (Department of Law, Dr. Harisingh Gour Central University) + Official DHSGSU Portal',
    navigationQuery: 'Department of Law, Dr. Harisingh Gour Central University, Sagar',
    isEventVenue: true,
    building: 'Department of Law',
  },
  {
    id: 'dept-commerce',
    name: 'Department of Commerce',
    plusCode: 'RQFC+VGF',
    category: 'Academic',
    latitude: 23.8246827,
    longitude: 78.7712887,
    description: 'Academic department of Commerce at Dr. Harisingh Gour Vishwavidyalaya.',
    address: 'RQFC+VGF, Dr. Harisingh Gour Central University, Sagar, Madhya Pradesh 470003',
    verified: 'verified',
    source: 'Google Maps Place (RQFC+VGF Department of Commerce, Dr. Harisingh Gour Central University)',
    navigationQuery: 'Department of Commerce, Dr. Harisingh Gour Central University, Sagar',
    isEventVenue: true,
    building: 'Department of Commerce',
  },
  {
    id: 'dept-criminology',
    name: 'Department of Criminology and Forensic Science',
    plusCode: 'RQFM+76Q',
    category: 'Academic',
    latitude: 23.8232008,
    longitude: 78.7831200,
    description: 'Academic department of Criminology and Forensic Science at Dr. Harisingh Gour Vishwavidyalaya.',
    address: 'RQFM+76Q, SH 15A, Dr. Harisingh Gour Central University, Patheriya Jat, Sagar, Madhya Pradesh 470001',
    verified: 'verified',
    source: 'Google Maps Place (RQFM+76Q Department of Criminology and forensic science)',
    navigationQuery: 'Department of Criminology and forensic science, Dr. Harisingh Gour Central University, Sagar',
    isEventVenue: true,
    building: 'Department of Criminology and Forensic Science',
  },
  {
    id: 'acharya-shankar-bhawan',
    name: 'Aacharya Shankar Bhawan',
    plusCode: 'RQFC+RR5',
    category: 'Academic',
    latitude: 23.8245133,
    longitude: 78.7721063,
    description: 'Academic building on the Dr. Harisingh Gour Vishwavidyalaya campus.',
    address: 'RQFC+RR5, Dr. Harisingh Gour Central University, Sagar, Madhya Pradesh 470003',
    verified: 'verified',
    source: 'Google Maps Place (RQFC+RR5 Aacharya Shankar Bhawan, Dr. Harisingh Gour Central University)',
    navigationQuery: 'Aacharya Shankar Bhawan, Dr. Harisingh Gour Central University, Sagar',
    isEventVenue: true,
    building: 'Aacharya Shankar Bhawan',
  },
  {
    id: 'dept-hindi',
    name: 'Department of Hindi',
    plusCode: 'RQGC+39W',
    category: 'Academic',
    latitude: 23.8252455,
    longitude: 78.7709621,
    description: 'Academic department of Hindi at Dr. Harisingh Gour Vishwavidyalaya.',
    address: 'RQGC+39W, Dr. Harisingh Gour Central University, Sagar, Madhya Pradesh 470003',
    verified: 'verified',
    source: 'Google Maps Place (RQGC+39W Department of Hindi, Dr. Harisingh Gour Central University)',
    navigationQuery: 'Department of Hindi, Dr. Harisingh Gour Central University, Sagar',
    isEventVenue: true,
    building: 'Department of Hindi',
  },
  {
    id: 'dept-english',
    name: 'Department of English and European Languages',
    plusCode: 'RQFC+GF',
    category: 'Academic',
    latitude: 23.8238690,
    longitude: 78.7712073,
    description: 'Academic department of English and European Languages at Dr. Harisingh Gour Vishwavidyalaya.',
    address: 'RQFC+GF, Dr. Harisingh Gour Central University, Sagar, Madhya Pradesh 470003',
    verified: 'verified',
    source: 'Google Maps Place (RQFC+GF Department of English and European Languages)',
    navigationQuery: 'Department of English and European Languages, Dr. Harisingh Gour Central University, Sagar',
    isEventVenue: true,
    building: 'Department of English and European Languages',
  },
  {
    id: 'dept-pharmacy',
    name: 'Department of Pharmaceutical Sciences',
    plusCode: 'RQHF+FQ2',
    category: 'Academic',
    latitude: 23.8286390,
    longitude: 78.7744060,
    description: 'Academic department of Pharmaceutical Sciences at Dr. Harisingh Gour Vishwavidyalaya.',
    address: 'RQHF+FQ2, Dr. Harisingh Gour Central University, Sagar, Madhya Pradesh 470003',
    verified: 'verified',
    source: 'Google Maps Place (RQHF+FQ2 Department Of Pharmaceutical Sciences)',
    navigationQuery: 'Department Of Pharmaceutical Sciences, Dr. Harisingh Gour Central University, Sagar',
    isEventVenue: true,
    building: 'Department of Pharmaceutical Sciences',
  },
  {
    id: 'dept-physics',
    name: 'Department of Physics',
    plusCode: 'RQHF+PG9',
    category: 'Academic',
    latitude: 23.8285625,
    longitude: 78.7711009,
    description: 'Academic department of Physics at Dr. Harisingh Gour Vishwavidyalaya.',
    address: 'RQHF+PG9, Dr. Harisingh Gour Central University, Sagar, Madhya Pradesh 470003',
    verified: 'verified',
    source: 'Google Maps Place (RQHF+PG9 Department of Physics, Dr. Harisingh Gour Central University)',
    navigationQuery: 'Department of Physics, Dr. Harisingh Gour Central University, Sagar',
    isEventVenue: true,
    building: 'Department of Physics',
  },
  {
    id: 'dept-chemistry',
    name: 'Department of Chemistry',
    plusCode: 'RQHF+CG8',
    category: 'Academic',
    latitude: 23.8285425,
    longitude: 78.7738209,
    description: 'Academic department of Chemistry at Dr. Harisingh Gour Vishwavidyalaya.',
    address: 'RQHF+CG8, Dr. Harisingh Gour Central University, Sagar, Madhya Pradesh 470003',
    verified: 'verified',
    source: 'Google Maps Place (RQHF+CG8 Department of Chemistry, Dr. Harisingh Gour Central University)',
    navigationQuery: 'Department of Chemistry, Dr. Harisingh Gour Central University, Sagar',
    isEventVenue: true,
    building: 'Department of Chemistry',
  },
  {
    id: 'dept-botany',
    name: 'Department of Botany',
    plusCode: 'RQHF+VX3',
    category: 'Academic',
    latitude: 23.8296415,
    longitude: 78.7749213,
    description: 'Academic department of Botany at Dr. Harisingh Gour Vishwavidyalaya.',
    address: 'RQHF+VX3, SH 15A, Dr. Harisingh Gour Central University, Sagar, Madhya Pradesh 470003',
    verified: 'verified',
    source: 'Google Maps Place (RQHF+VX3 Department of Botany, Dr. Harisingh Gour Central University)',
    navigationQuery: 'Department of Botany, Dr. Harisingh Gour Central University, Sagar',
    isEventVenue: true,
    building: 'Department of Botany',
  },
  {
    id: 'dept-geology',
    name: 'Department of Applied Geology',
    plusCode: 'RQHF+J3J',
    category: 'Academic',
    latitude: 23.8290884,
    longitude: 78.7726455,
    description: 'Academic department of Applied Geology at Dr. Harisingh Gour Vishwavidyalaya.',
    address: 'RQHF+J3J, SH 15A, Dr. Harisingh Gour Central University, Sagar, Madhya Pradesh 470003',
    verified: 'verified',
    source: 'Google Maps Place (RQHF+J3J Department of Applied Geology, Dr. Harisingh Gour Central University)',
    navigationQuery: 'Department of Applied Geology, Dr. Harisingh Gour Central University, Sagar',
    isEventVenue: true,
    building: 'Department of Applied Geology',
  },
  {
    id: 'university-hospital',
    name: 'University Hospital',
    plusCode: 'RQFF+RXC',
    category: 'Medical',
    latitude: 23.8245604,
    longitude: 78.7748831,
    description: 'University hospital and health centre at Dr. Harisingh Gour Vishwavidyalaya.',
    address: 'RQFF+RXC, SH 15A, Dr. Harisingh Gour Central University, Sagar, Madhya Pradesh 470003',
    verified: 'verified',
    source: 'Google Maps Place (RQFF+RXC University Hospital, Dr. Harisingh Gour Central University)',
    navigationQuery: 'University Hospital, Dr. Harisingh Gour Central University, Sagar',
    isEventVenue: false,
    building: 'University Hospital',
  },
  {
    id: 'university-guest-house',
    name: 'Guest House / Visitors House',
    plusCode: 'RQGC+7R6',
    category: 'Administration',
    latitude: 23.8256706,
    longitude: 78.7720095,
    description: 'University guest house and visitors house at Dr. Harisingh Gour Vishwavidyalaya.',
    address: 'RQGC+7R6, Dr. Harisingh Gour Central University, Sagar, Madhya Pradesh 470003',
    verified: 'verified',
    source: 'Google Maps Place (RQGC+7R6 Guest House / Visitors House, Dr. Harisingh Gour Central University)',
    navigationQuery: 'Guest House, Dr. Harisingh Gour Central University, Sagar',
    isEventVenue: false,
    building: 'Guest House / Visitors House',
  },
  {
    id: 'hostel-tagore',
    name: 'Tagore Hostel',
    category: 'Hostel',
    latitude: 23.8215625,
    longitude: 78.7711875,
    description: 'University boys hostel at Dr. Harisingh Gour Vishwavidyalaya.',
    address: 'Dr. Harisingh Gour Central University, Patheriya Jat, Sagar, Madhya Pradesh 470003',
    verified: 'verified',
    source: 'Google Maps Place (Tagore Hostel, Dr. Harisingh Gour Central University)',
    navigationQuery: 'Tagore Hostel, Dr. Harisingh Gour Central University, Sagar',
    isEventVenue: false,
    building: 'Tagore Hostel',
  },
  {
    id: 'hostel-nivedita',
    name: 'Nivedita Girls Hostel',
    plusCode: 'RQHJ+W5',
    category: 'Hostel',
    latitude: 23.8297801,
    longitude: 78.7803686,
    description: 'University girls hostel at Dr. Harisingh Gour Vishwavidyalaya.',
    address: 'RQHJ+W5, Professors Colony, Dr. Harisingh Gour Central University, Sagar, Madhya Pradesh 470001',
    verified: 'verified',
    source: 'Google Maps Place (RQHJ+W5 Nivedita Girls Hostel, Professors Colony, Sagar)',
    navigationQuery: 'Nivedita Girls Hostel, Professors Colony, Sagar',
    isEventVenue: false,
    building: 'Nivedita Girls Hostel',
  },

  // ============================================================================
  // 2. LOCATION VERIFICATION REQUIRED (Not individually pinned on Google Maps)
  // Omitted from Verified Map Pins so zero approximate markers are placed
  // ============================================================================
  {
    id: 'venue-swarna-jayanti',
    name: 'Swarn Jayanti Hall',
    secondaryName: 'Golden Jubilee Hall',
    category: 'Event Venue',
    latitude: null,
    longitude: null,
    description: 'University hall referenced in official DHSGSU notices. Exact building coordinate verification required on Google Maps.',
    address: 'Dr. Harisingh Gour Vishwavidyalaya, Sagar, Madhya Pradesh 470003',
    verified: 'unverified',
    source: 'Official DHSGSU Notices (Location verification required — not individually indexed as a separate pin on Google Maps)',
    navigationQuery: 'Dr. Harisingh Gour Vishwavidyalaya, University Road, Sagar, Madhya Pradesh',
    isEventVenue: true,
    building: 'Swarn Jayanti Hall',
  },
];

// Reference date for realistic simulation: today is 2026-09-30
export const INITIAL_EVENTS: CampusEvent[] = [
  {
    _id: 'evt-1',
    title: 'Deep Learning & Computer Vision on Satellite Imagery Workshop',
    description: 'Hands-on workshop organized by the Department of Computer Science and Applications (DCSA) covering PyTorch, convolutional architectures, and remote sensing datasets.',
    category: 'Workshop',
    eventMode: 'HYBRID',
    organizerId: 'org-1',
    organizerName: 'Dr. Alok Sahay',
    organizerEmail: 'alok.sahay@dhsgsu.edu.in',
    venue: 'Department of Computer Science and Applications',
    venueId: 'venue-dcsa-lab',
    startTime: '2026-10-16T10:00:00Z',
    endTime: '2026-10-16T13:00:00Z',
    capacity: 60,
    registrationCount: 42,
    registrationDeadline: '2026-10-15T23:59:00Z',
    tags: ['AI', 'Computer Vision', 'PyTorch', 'DCSA', 'DHSGSU'],
    coverImage: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80',
    status: 'ONGOING',
    eligibility: 'Enrolled B.Tech, M.Tech, MCA, and M.Sc students of DHSGSU',
    specialInstructions: 'Bring university identity card and personal laptop with Python 3.11 installed.',
    departmentScope: 'Department of Computer Science and Applications',
    certificateRequired: true,
    minParticipationPercent: 80,
    attendanceSessionStatus: 'ACTIVE',
    attendanceStartedAt: '2026-10-04T09:00:00Z',
    createdAt: '2026-09-10T08:00:00Z',
    updatedAt: '2026-10-04T09:00:00Z',
  },
  {
    _id: 'evt-2',
    title: '78th Gour Memorial National Science & Innovation Symposium',
    description: 'National science symposium honoring the university founder, Sir Dr. Hari Singh Gour, featuring keynote addresses on nanomaterials, renewable energy, and scientific research.',
    category: 'Seminar',
    eventMode: 'OFFLINE',
    organizerId: 'org-2',
    organizerName: 'Prof. R.K. Trivedi',
    organizerEmail: 'rk.trivedi@dhsgsu.edu.in',
    venue: 'Abhimanch Sabhagar',
    venueId: 'venue-abhimanch',
    startTime: '2026-10-18T11:30:00Z',
    endTime: '2026-10-18T15:30:00Z',
    capacity: 500,
    registrationCount: 380,
    registrationDeadline: '2026-10-17T18:00:00Z',
    tags: ['Gour Memorial', 'National Symposium', 'Sciences', 'Keynote', 'DHSGSU'],
    coverImage: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
    eligibility: 'Open to all university students, research scholars, and faculty members',
    specialInstructions: 'Formal university dress code. Please be seated 15 minutes before commencement.',
    departmentScope: 'Faculty of Science & Academic Council',
    certificateRequired: true,
    minParticipationPercent: 80,
    attendanceSessionStatus: 'NOT_STARTED',
    createdAt: '2026-09-01T10:00:00Z',
    updatedAt: '2026-09-28T09:00:00Z',
  },
  {
    _id: 'evt-3',
    title: 'Bundelkhand Folk Heritage & University Youth Festival (Utsav 2026)',
    description: 'An evening celebrating Bundelkhand folk dance, classical music, theatrical drama, and instrumental performances by university cultural troupes across departments.',
    category: 'Cultural',
    eventMode: 'OFFLINE',
    organizerId: 'org-1',
    organizerName: 'Dr. Alok Sahay',
    organizerEmail: 'alok.sahay@dhsgsu.edu.in',
    venue: 'Abhimanch Sabhagar',
    venueId: 'venue-abhimanch',
    startTime: '2026-10-02T17:00:00Z',
    endTime: '2026-10-02T20:00:00Z',
    capacity: 400,
    registrationCount: 290,
    registrationDeadline: '2026-10-01T23:59:00Z',
    tags: ['Cultural', 'Bundelkhand', 'Music', 'Youth Festival', 'Dance'],
    coverImage: 'https://images.unsplash.com/photo-1469488865564-c2de10f69f96?auto=format&fit=crop&w=800&q=80',
    status: 'COMPLETED',
    eligibility: 'All students with valid DHSGSU identity card',
    specialInstructions: 'Digital event pass must be shown at the Abhimanch Sabhagar entrance.',
    departmentScope: 'University Cultural Affairs Council',
    certificateRequired: true,
    minParticipationPercent: 80,
    attendanceSessionStatus: 'CLOSED',
    attendanceStartedAt: '2026-10-02T17:00:00Z',
    attendanceClosedAt: '2026-10-02T20:00:00Z',
    createdAt: '2026-09-15T11:00:00Z',
    updatedAt: '2026-10-02T20:30:00Z',
  },
  {
    _id: 'evt-4',
    title: 'All-Madhya Pradesh Inter-University Hackathon: Smart Campus & AgriTech',
    description: '36-hour inter-university hackathon where student teams build software and IoT solutions for agriculture, energy, and digital campus services.',
    category: 'Coding',
    eventMode: 'HYBRID',
    organizerId: 'org-1',
    organizerName: 'Dr. Alok Sahay',
    organizerEmail: 'alok.sahay@dhsgsu.edu.in',
    venue: 'Jawaharlal Nehru Central Library',
    venueId: 'venue-central-library',
    startTime: '2026-10-20T09:00:00Z',
    endTime: '2026-10-21T21:00:00Z',
    capacity: 100,
    registrationCount: 78,
    registrationDeadline: '2026-10-19T18:00:00Z',
    tags: ['Hackathon', 'Coding', 'AgriTech', 'Smart Campus', 'DHSGSU'],
    coverImage: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
    eligibility: 'Teams of 2 to 4 enrolled university students',
    specialInstructions: 'Bring extensions and personal laptops. Valid university ID card mandatory.',
    departmentScope: 'Department of Computer Science and Applications',
    certificateRequired: true,
    minParticipationPercent: 85,
    attendanceSessionStatus: 'NOT_STARTED',
    createdAt: '2026-09-12T09:30:00Z',
    updatedAt: '2026-09-26T14:20:00Z',
  },
  {
    _id: 'evt-5',
    title: 'Inter-Departmental Cricket Championship & Athletic Trials',
    description: 'Annual inter-departmental sports tournament held at Abdul Gani Khan Stadium (Dr. Hari Singh Gour University Stadium). Selection trials for inter-university athletics and cricket.',
    category: 'Sports',
    eventMode: 'OFFLINE',
    organizerId: 'org-2',
    organizerName: 'Prof. R.K. Trivedi',
    organizerEmail: 'rk.trivedi@dhsgsu.edu.in',
    venue: 'Abdul Gani Khan Stadium',
    venueId: 'venue-stadium',
    startTime: '2026-10-22T08:00:00Z',
    endTime: '2026-10-24T18:00:00Z',
    capacity: 600,
    registrationCount: 310,
    registrationDeadline: '2026-10-21T20:00:00Z',
    tags: ['Cricket', 'Athletics', 'Sports', 'Abdul Gani Khan Stadium', 'Trials'],
    coverImage: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
    eligibility: 'Open to registered student athletes representing departmental teams',
    specialInstructions: 'Athletic wear mandatory. Bring university ID card.',
    departmentScope: 'Department of Physical Education & Sports',
    certificateRequired: true,
    minParticipationPercent: 80,
    attendanceSessionStatus: 'NOT_STARTED',
    createdAt: '2026-09-18T14:00:00Z',
    updatedAt: '2026-09-28T11:00:00Z',
  },
  {
    _id: 'evt-6',
    title: 'Campus Placement & Corporate Readiness Conclave 2026',
    description: 'Central training and placement orientation featuring industry speakers, resume clinics, mock technical interviews, and career guidance sessions.',
    category: 'Placement',
    eventMode: 'HYBRID',
    organizerId: 'org-1',
    organizerName: 'Dr. Alok Sahay',
    organizerEmail: 'alok.sahay@dhsgsu.edu.in',
    venue: 'Abhimanch Sabhagar',
    venueId: 'venue-abhimanch',
    startTime: '2026-10-25T09:30:00Z',
    endTime: '2026-10-25T17:00:00Z',
    capacity: 450,
    registrationCount: 420,
    registrationDeadline: '2026-10-24T23:59:00Z',
    tags: ['Placement', 'Career', 'Interviews', 'Corporate', 'Training'],
    coverImage: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
    eligibility: 'Final and Pre-Final Year students of undergraduate and postgraduate programs',
    specialInstructions: 'Carry copies of your university resume and ID card.',
    departmentScope: 'Training & Placement Cell, DHSGSU',
    certificateRequired: true,
    minParticipationPercent: 80,
    attendanceSessionStatus: 'NOT_STARTED',
    createdAt: '2026-09-14T10:00:00Z',
    updatedAt: '2026-09-29T10:30:00Z',
  },
  {
    _id: 'evt-7',
    title: 'Hands-on Workshop: Drone Mapping & Remote Sensing in Bundelkhand',
    description: 'Practical training on geospatial survey drones, multispectral imaging, and GIS mapping conducted at the Department of General and Applied Geography.',
    category: 'Technology',
    eventMode: 'OFFLINE',
    organizerId: 'org-2',
    organizerName: 'Prof. R.K. Trivedi',
    organizerEmail: 'rk.trivedi@dhsgsu.edu.in',
    venue: 'Department of General and Applied Geography',
    venueId: 'venue-geography-dept',
    startTime: '2026-10-27T10:00:00Z',
    endTime: '2026-10-27T15:30:00Z',
    capacity: 80,
    registrationCount: 65,
    registrationDeadline: '2026-10-26T20:00:00Z',
    tags: ['Drones', 'GIS', 'Remote Sensing', 'Technology', 'Geography'],
    coverImage: 'https://images.unsplash.com/photo-1527977966376-1c8408f9f108?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
    eligibility: 'Students of Science, Geography, Geology, and Engineering faculties',
    specialInstructions: 'Bring university ID card and field notebook.',
    departmentScope: 'Department of General and Applied Geography',
    certificateRequired: true,
    minParticipationPercent: 80,
    attendanceSessionStatus: 'NOT_STARTED',
    createdAt: '2026-09-20T12:00:00Z',
    updatedAt: '2026-09-28T14:00:00Z',
  },
  {
    _id: 'evt-8',
    title: 'Student Venture Pitch & Entrepreneurship Showcase',
    description: 'Students present early-stage technology, social, and commercial project ideas before faculty and industry mentors.',
    category: 'Entrepreneurship',
    eventMode: 'OFFLINE',
    organizerId: 'org-1',
    organizerName: 'Dr. Alok Sahay',
    organizerEmail: 'alok.sahay@dhsgsu.edu.in',
    venue: 'Department of Commerce',
    venueId: 'dept-commerce',
    startTime: '2026-10-29T10:00:00Z',
    endTime: '2026-10-29T16:00:00Z',
    capacity: 100,
    registrationCount: 52,
    registrationDeadline: '2026-10-28T18:00:00Z',
    tags: ['Startup', 'Pitch', 'Commerce', 'Entrepreneurship'],
    coverImage: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
    eligibility: 'Any enrolled student or multidisciplinary team with a pitch deck',
    specialInstructions: 'Pitches limited to 7 minutes followed by 5 minutes Q&A.',
    departmentScope: 'Department of Commerce',
    certificateRequired: true,
    minParticipationPercent: 75,
    attendanceSessionStatus: 'NOT_STARTED',
    createdAt: '2026-09-21T09:00:00Z',
    updatedAt: '2026-09-29T11:00:00Z',
  },
  {
    _id: 'evt-9',
    title: 'National Moot Court Competition: Constitutional Law in the Digital Age',
    description: 'National moot court competition focusing on constitutional privacy rights and digital jurisprudence at the Department of Law.',
    category: 'Competition',
    eventMode: 'OFFLINE',
    organizerId: 'org-2',
    organizerName: 'Prof. R.K. Trivedi',
    organizerEmail: 'rk.trivedi@dhsgsu.edu.in',
    venue: 'Department of Law',
    venueId: 'venue-law-hall',
    startTime: '2026-11-02T09:00:00Z',
    endTime: '2026-11-03T18:00:00Z',
    capacity: 120,
    registrationCount: 94,
    registrationDeadline: '2026-10-31T23:59:00Z',
    tags: ['Moot Court', 'Law', 'Constitution', 'Competition', 'DHSGSU'],
    coverImage: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
    eligibility: 'LL.B and B.A. LL.B student teams',
    specialInstructions: 'Memorial submission due 48 hours prior to oral rounds.',
    departmentScope: 'Department of Law',
    certificateRequired: true,
    minParticipationPercent: 85,
    attendanceSessionStatus: 'NOT_STARTED',
    createdAt: '2026-09-22T10:00:00Z',
    updatedAt: '2026-09-29T13:00:00Z',
  },
  {
    _id: 'evt-10',
    title: 'University Astronomy & Sky Observation Session',
    description: 'Evening sky observation and introductory astrophysics session organized by the Department of Physics.',
    category: 'Club',
    eventMode: 'OFFLINE',
    organizerId: 'org-1',
    organizerName: 'Dr. Alok Sahay',
    organizerEmail: 'alok.sahay@dhsgsu.edu.in',
    venue: 'Department of Physics',
    venueId: 'dept-physics',
    startTime: '2026-11-06T19:00:00Z',
    endTime: '2026-11-06T22:30:00Z',
    capacity: 150,
    registrationCount: 110,
    registrationDeadline: '2026-11-05T18:00:00Z',
    tags: ['Astronomy', 'Physics', 'Night Sky', 'Club', 'DHSGSU'],
    coverImage: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
    eligibility: 'Open to all enrolled students and faculty members',
    specialInstructions: 'Bring university ID card.',
    departmentScope: 'Department of Physics',
    certificateRequired: false,
    minParticipationPercent: 75,
    attendanceSessionStatus: 'NOT_STARTED',
    createdAt: '2026-09-23T11:00:00Z',
    updatedAt: '2026-09-29T15:00:00Z',
  },
  {
    _id: 'evt-11',
    title: 'Human-Centered Design & Interactive Systems Workshop',
    description: 'A 2-day studio on information architecture, usability, and accessibility standards for digital applications.',
    category: 'Academic',
    eventMode: 'ONLINE',
    organizerId: 'org-1',
    organizerName: 'Dr. Alok Sahay',
    organizerEmail: 'alok.sahay@dhsgsu.edu.in',
    venue: 'Department of Computer Science and Applications',
    venueId: 'venue-dcsa-lab',
    startTime: '2026-11-08T10:00:00Z',
    endTime: '2026-11-08T13:00:00Z',
    capacity: 45,
    registrationCount: 38,
    registrationDeadline: '2026-11-07T20:00:00Z',
    tags: ['Design', 'UI/UX', 'Accessibility', 'Academic', 'DCSA'],
    coverImage: 'https://images.unsplash.com/photo-1581291518655-9523c932edcf?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
    eligibility: 'All students interested in software interface engineering',
    specialInstructions: 'Online workshop session with live attendance heartbeat validation.',
    departmentScope: 'Department of Computer Science and Applications',
    certificateRequired: true,
    minParticipationPercent: 80,
    attendanceSessionStatus: 'NOT_STARTED',
    createdAt: '2026-09-24T14:00:00Z',
    updatedAt: '2026-09-29T16:00:00Z',
  },
  {
    _id: 'evt-12',
    title: 'Annual Hindi & Bundeli Sahitya Sabha: Heritage Poetry and Dialogue',
    description: 'Literary gathering celebrating Hindi and Bundeli poetry recitations and panel discussions on regional literature.',
    category: 'Other',
    eventMode: 'OFFLINE',
    organizerId: 'org-2',
    organizerName: 'Prof. R.K. Trivedi',
    organizerEmail: 'rk.trivedi@dhsgsu.edu.in',
    venue: 'Department of Hindi',
    venueId: 'dept-hindi',
    startTime: '2026-11-11T14:00:00Z',
    endTime: '2026-11-11T18:00:00Z',
    capacity: 150,
    registrationCount: 88,
    registrationDeadline: '2026-11-10T18:00:00Z',
    tags: ['Literature', 'Hindi', 'Bundelkhand', 'Poetry', 'Heritage'],
    coverImage: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
    eligibility: 'Open to all university community members',
    specialInstructions: 'Students wishing to recite original poetry should register 30 minutes prior.',
    departmentScope: 'Department of Hindi',
    certificateRequired: true,
    minParticipationPercent: 80,
    attendanceSessionStatus: 'NOT_STARTED',
    createdAt: '2026-09-25T10:00:00Z',
    updatedAt: '2026-09-29T17:00:00Z',
  },
  {
    _id: 'evt-13',
    title: 'National Symposium on Quantum Cryptography & Post-Quantum Security',
    description: 'Proposed 1-day research seminar on lattice-based cryptography and secure digital infrastructure.',
    category: 'Seminar',
    eventMode: 'HYBRID',
    organizerId: 'org-1',
    organizerName: 'Dr. Alok Sahay',
    organizerEmail: 'alok.sahay@dhsgsu.edu.in',
    venue: 'Administrative Building',
    venueId: 'venue-gour-bhavan',
    startTime: '2026-11-15T10:30:00Z',
    endTime: '2026-11-15T16:30:00Z',
    capacity: 150,
    registrationCount: 0,
    registrationDeadline: '2026-11-13T18:00:00Z',
    tags: ['Cryptography', 'Security', 'Seminar', 'DCSA', 'Research'],
    coverImage: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=800&q=80',
    status: 'PENDING_REVIEW',
    eligibility: 'Postgraduate students, research scholars, and faculty members',
    specialInstructions: 'Submitted for DSW administrative review.',
    departmentScope: 'Department of Computer Science and Applications',
    certificateRequired: true,
    minParticipationPercent: 80,
    attendanceSessionStatus: 'NOT_STARTED',
    createdAt: '2026-09-29T18:00:00Z',
    updatedAt: '2026-09-29T18:00:00Z',
  },
  {
    _id: 'evt-14',
    title: 'Embedded Rust & RISC-V Microcontroller Lab Bootcamp',
    description: 'Hands-on laboratory workshop introducing memory-safe embedded systems programming on RISC-V development boards.',
    category: 'Workshop',
    eventMode: 'OFFLINE',
    organizerId: 'org-1',
    organizerName: 'Dr. Alok Sahay',
    organizerEmail: 'alok.sahay@dhsgsu.edu.in',
    venue: 'Department of Computer Science and Applications',
    venueId: 'venue-dcsa-lab',
    startTime: '2026-11-20T10:00:00Z',
    endTime: '2026-11-20T16:00:00Z',
    capacity: 60,
    registrationCount: 0,
    registrationDeadline: '2026-11-18T23:59:00Z',
    tags: ['Rust', 'Embedded', 'RISC-V', 'Workshop', 'Hardware'],
    coverImage: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=800&q=80',
    status: 'DRAFT',
    eligibility: 'B.Tech and MCA students',
    specialInstructions: 'Draft proposal being prepared by faculty convener.',
    departmentScope: 'Department of Computer Science and Applications',
    certificateRequired: true,
    minParticipationPercent: 80,
    attendanceSessionStatus: 'NOT_STARTED',
    createdAt: '2026-09-30T08:00:00Z',
    updatedAt: '2026-09-30T08:00:00Z',
  }
];

export const INITIAL_REGISTRATIONS: Registration[] = [
  {
    _id: 'reg-1',
    eventId: 'evt-1',
    userId: 'student-1',
    userName: 'Amit Sharma',
    userRollNumber: 'Y23141042',
    userDepartment: 'Department of Computer Science & Applications',
    userEmail: 'amit.sharma@dhsgsu.edu.in',
    status: 'CONFIRMED',
    registeredAt: '2026-09-20T14:30:00Z',
    qrToken: 'PARISAR-PASS-DL-CS042',
    checkedInAt: null,
  },
  {
    _id: 'reg-2',
    eventId: 'evt-2',
    userId: 'student-1',
    userName: 'Amit Sharma',
    userRollNumber: 'Y23141042',
    userDepartment: 'Department of Computer Science & Applications',
    userEmail: 'amit.sharma@dhsgsu.edu.in',
    status: 'CONFIRMED',
    registeredAt: '2026-09-22T09:15:00Z',
    qrToken: 'PARISAR-PASS-GM-CS042',
    checkedInAt: null,
  },
  {
    _id: 'reg-3',
    eventId: 'evt-3',
    userId: 'student-2',
    userName: 'Priya Patel',
    userRollNumber: 'Y23122018',
    userDepartment: 'Department of Electronics & Communication',
    userEmail: 'priya.patel@dhsgsu.edu.in',
    status: 'CONFIRMED',
    registeredAt: '2026-09-21T16:00:00Z',
    qrToken: 'PARISAR-PASS-UT-EC118',
    checkedInAt: '2026-10-02T17:05:00Z',
  },
  {
    _id: 'reg-4',
    eventId: 'evt-1',
    userId: 'student-3',
    userName: 'Rohan Mehra',
    userRollNumber: 'Y23141088',
    userDepartment: 'Department of Computer Science & Applications',
    userEmail: 'rohan.mehra@dhsgsu.edu.in',
    status: 'CONFIRMED',
    registeredAt: '2026-09-20T15:00:00Z',
    qrToken: 'PARISAR-PASS-DL-CS088',
    checkedInAt: '2026-10-04T09:05:00Z',
  }
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    _id: 'att-1',
    eventId: 'evt-1',
    registrationId: 'reg-4',
    userId: 'student-3',
    userName: 'Rohan Mehra',
    userRollNumber: 'Y23141088',
    userDepartment: 'Department of Computer Science & Applications',
    status: 'PRESENT',
    checkedInAt: '2026-10-04T09:05:00Z',
    checkedInBy: 'org-1',
    method: 'roster',
    participatedMinutes: 180,
    requiredMinutes: 144,
    totalEventMinutes: 180,
    participationPercent: 100,
    sessionStatus: 'COMPLETED',
    lastValidatedAt: '2026-10-04T11:47:00Z',
    eligibleForCertificate: true,
  },
  {
    _id: 'att-2',
    eventId: 'evt-3',
    registrationId: 'reg-3',
    userId: 'student-2',
    userName: 'Priya Patel',
    userRollNumber: 'Y23122018',
    userDepartment: 'Department of Electronics & Communication',
    status: 'PRESENT',
    checkedInAt: '2026-10-02T17:05:00Z',
    checkedInBy: 'org-1',
    method: 'roster',
    participatedMinutes: 180,
    requiredMinutes: 144,
    totalEventMinutes: 180,
    participationPercent: 100,
    sessionStatus: 'COMPLETED',
    lastValidatedAt: '2026-10-02T19:50:00Z',
    eligibleForCertificate: true,
  }
];

export const INITIAL_CERTIFICATES: Certificate[] = [
  {
    _id: 'cert-1',
    eventId: 'evt-past-1',
    eventTitle: 'National Workshop on High-Performance Distributed Computing',
    userId: 'student-1',
    userName: 'Amit Sharma',
    userRollNumber: 'Y23141042',
    department: 'Department of Computer Science & Applications',
    certificateUrl: '/certificates/cert-hp-dc-042.pdf',
    verificationCode: 'DHSGSU-CERT-2026-CS8841',
    issuedAt: '2026-08-28T16:00:00Z',
    certificateType: 'EXCELLENCE',
    issueAuthorizedBy: 'Dr. Alok Sahay, Faculty Convener',
    academicAuthority: "Office of the Dean of Students' Welfare (DSW), DHSGSU",
  },
  {
    _id: 'cert-2',
    eventId: 'evt-past-2',
    eventTitle: 'Inter-University Bundelkhand Science Hackathon 2025',
    userId: 'student-1',
    userName: 'Amit Sharma',
    userRollNumber: 'Y23141042',
    department: 'Department of Computer Science & Applications',
    certificateUrl: '/certificates/cert-hack-042.pdf',
    verificationCode: 'DHSGSU-CERT-2025-HK3319',
    issuedAt: '2025-11-15T18:00:00Z',
    certificateType: 'MERIT',
    issueAuthorizedBy: 'Prof. R.K. Trivedi, Organizing Secretary',
    academicAuthority: "Office of the Dean of Students' Welfare (DSW), DHSGSU",
  }
];

export const INITIAL_NOTIFICATIONS: CampusNotification[] = [
  {
    _id: 'notif-1',
    userId: 'student-1',
    eventId: 'evt-1',
    type: 'REGISTRATION_CONFIRMED',
    title: 'Registration Confirmed: Deep Learning Workshop',
    message: 'Your seat at the Department of Computer Science & Applications (DCSA) is confirmed. Your PARISAR digital pass is ready for door check-in.',
    read: false,
    createdAt: '2026-09-29T14:30:00Z',
  },
  {
    _id: 'notif-2',
    userId: 'student-1',
    eventId: 'evt-1',
    type: 'VENUE_CHANGED',
    title: 'Laboratory Preparation Notice',
    message: 'Please ensure PyTorch and Python 3.11 are installed on your personal laptops before arriving at the Department of Computer Science & Applications (DCSA).',
    read: false,
    createdAt: '2026-09-30T07:15:00Z',
  },
  {
    _id: 'notif-3',
    userId: 'student-1',
    eventId: 'evt-2',
    type: 'EVENT_REMINDER',
    title: 'Event Today: 78th Gour Memorial Symposium',
    message: 'Starting at 11:30 AM in Abhimanch Sabhagar. Please arrive 15 minutes before the academic procession begins.',
    read: true,
    createdAt: '2026-09-30T06:00:00Z',
  }
];

export const INITIAL_ACHIEVEMENTS: AchievementBadge[] = [
  {
    id: 'ach-1',
    name: 'DHSGSU Campus Explorer',
    description: 'Participated in university events across 3 distinct academic faculties on Patharia Hills.',
    iconName: 'Compass',
    category: 'Exploration',
    unlockedAt: '2026-08-28T16:00:00Z',
    progress: 3,
    total: 3,
  },
  {
    id: 'ach-2',
    name: 'Advanced Computing Scholar',
    description: 'Successfully completed 30+ verified lab workshop hours organized by DCSA.',
    iconName: 'Cpu',
    category: 'Workshops',
    unlockedAt: '2026-09-15T12:00:00Z',
    progress: 30,
    total: 30,
  },
  {
    id: 'ach-3',
    name: 'Gour Memorial Honoree',
    description: 'Attended the prestigious annual university founder commemoration symposium.',
    iconName: 'Award',
    category: 'Academic',
    progress: 2,
    total: 3,
  },
  {
    id: 'ach-4',
    name: 'Hackathon Contender',
    description: 'Engineered a working software prototype during an inter-university coding competition.',
    iconName: 'Zap',
    category: 'Coding',
    unlockedAt: '2025-11-15T18:00:00Z',
    progress: 1,
    total: 1,
  }
];

export const PASSPORT_ACHIEVEMENTS = INITIAL_ACHIEVEMENTS;

export const INITIAL_FEEDBACK: EventFeedback[] = [
  {
    _id: 'fb-1',
    eventId: 'evt-past-1',
    userId: 'student-1',
    userName: 'Amit Sharma',
    rating: 5,
    comment: 'Exceptional hands-on training in the DCSA lab. The practical GPU pipelines were immediately applicable.',
    createdAt: '2026-08-29T10:00:00Z',
  },
  {
    _id: 'fb-2',
    eventId: 'evt-past-1',
    userId: 'student-2',
    userName: 'Priya Patel',
    rating: 5,
    comment: 'Clear explanations and excellent faculty mentoring from Dr. Alok Sahay.',
    createdAt: '2026-08-29T11:30:00Z',
  }
];
