import { 
  User, 
  CampusEvent, 
  CampusVenue, 
  Registration, 
  AttendanceRecord, 
  Certificate, 
  CampusNotification, 
  EventFeedback,
  AchievementBadge
} from '../types';

export const INITIAL_USERS: User[] = [
  {
    _id: 'student-1',
    name: 'Amit Sharma',
    email: 'amit.sharma@dhsgsu.edu.in',
    rollNumber: 'Y23141042',
    department: 'Department of Computer Science & Applications',
    semester: 6,
    role: 'student',
    interests: ['Technology', 'Coding', 'Entrepreneurship', 'Workshop'],
    profileImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
    phone: '+91 98260 12345',
    createdAt: '2025-08-01T09:00:00Z',
    updatedAt: '2026-03-15T11:20:00Z',
  },
  {
    _id: 'student-2',
    name: 'Priya Patel',
    email: 'priya.patel@dhsgsu.edu.in',
    rollNumber: 'Y23122018',
    department: 'Department of Electronics & Communication',
    semester: 4,
    role: 'student',
    interests: ['Cultural', 'Sports', 'Seminar'],
    profileImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=250&q=80',
    phone: '+91 98260 67890',
    createdAt: '2025-08-10T10:00:00Z',
    updatedAt: '2026-02-18T14:10:00Z',
  },
  {
    _id: 'student-3',
    name: 'Rohan Mehra',
    email: 'rohan.mehra@dhsgsu.edu.in',
    rollNumber: 'Y23141088',
    department: 'Department of Computer Science & Applications',
    semester: 6,
    role: 'student',
    interests: ['Coding', 'Competition', 'Technology'],
    profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80',
    phone: '+91 94250 11223',
    createdAt: '2025-08-05T09:00:00Z',
    updatedAt: '2026-02-20T10:00:00Z',
  },
  {
    _id: 'org-1',
    name: 'Dr. Alok Sahay',
    email: 'alok.sahay@dhsgsu.edu.in',
    department: 'Department of Computer Science & Applications (DCSA)',
    role: 'organizer',
    designation: 'Associate Professor & Faculty Convener',
    organization: 'DHSGSU Centre for Computing & Innovation',
    interests: ['Technology', 'Coding', 'Workshop', 'Seminar'],
    profileImage: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=250&q=80',
    phone: '+91 75822 64201',
    createdAt: '2024-06-01T09:00:00Z',
    updatedAt: '2026-01-10T09:00:00Z',
  },
  {
    _id: 'org-2',
    name: 'Prof. R.K. Trivedi',
    email: 'rk.trivedi@dhsgsu.edu.in',
    department: 'Department of Technology & Engineering',
    role: 'organizer',
    designation: 'Professor & Dean, Faculty of Engineering & Technology',
    organization: 'DHSGSU Robotics & Automation Council',
    interests: ['Competition', 'Workshop', 'Sports'],
    profileImage: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=250&q=80',
    phone: '+91 75822 64205',
    createdAt: '2024-07-15T09:00:00Z',
    updatedAt: '2026-02-12T10:00:00Z',
  },
  {
    _id: 'admin-1',
    name: 'Prof. S.P. Gautam',
    email: 'dsw@dhsgsu.edu.in',
    department: "Office of the Dean of Students' Welfare (DSW)",
    role: 'admin',
    designation: "Dean of Students' Welfare & Proctor",
    organization: 'Dr. Harisingh Gour Vishwavidyalaya, Sagar (M.P.)',
    interests: ['Academic', 'Administration', 'Governance'],
    profileImage: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=250&q=80',
    phone: '+91 75822 64400',
    createdAt: '2023-01-01T09:00:00Z',
    updatedAt: '2026-01-01T09:00:00Z',
  }
];

export const CAMPUS_VENUES: CampusVenue[] = [
  {
    id: 'venue-swarna-jayanti',
    name: 'Swarna Jayanti Auditorium',
    building: 'Central Administrative Complex, Patharia Hills',
    floor: 'Main Ground Floor, Golden Jubilee Wing',
    capacity: 800,
    coordinates: { x: 50, y: 52 },
    features: ['800-Seat Tiered Acoustics', 'Dual Hi-Def Laser Projectors', 'Green Rooms', 'Centralized HVAC', 'Accessible Ramps'],
    directions: 'Directly opposite Gour Bhavan, Main Central Gate 1 on Patharia Hills campus.',
  },
  {
    id: 'venue-dcsa-lab',
    name: 'Turing Advanced Computing Lab',
    building: 'Department of Computer Science & Applications (DCSA)',
    floor: '2nd Floor, Room 204',
    capacity: 85,
    coordinates: { x: 32, y: 28 },
    features: ['High-Performance Workstations', 'Gigabit NKN Internet', 'Smart Interactive Podium', 'Dual Monitors'],
    directions: 'Take South Staircase of DCSA building to 2nd floor, turn right adjacent to AI Research Cell.',
  },
  {
    id: 'venue-cv-raman',
    name: 'Prof. C.V. Raman Science Lecture Theatre',
    building: 'School of Chemical & Physical Sciences (Science Block 1)',
    floor: '1st Floor, Amphitheatre 102',
    capacity: 220,
    coordinates: { x: 68, y: 35 },
    features: ['Stepped Amphitheatre Seating', 'Live Experiment Demonstration Stage', 'Acoustic Surround', 'Audio Recorders'],
    directions: 'Enter Science Block 1 via North Portico, follow signs to Department of Physics.',
  },
  {
    id: 'venue-gour-bhavan',
    name: 'Gour Bhavan Senate & Conference Hall',
    building: 'Administrative Head Office, Patharia Hills',
    floor: 'Ground Floor, Vice-Chancellor Wing',
    capacity: 150,
    coordinates: { x: 45, y: 40 },
    features: ['Executive Round-Table Setup', 'Simultaneous Interpretation', 'Video Conferencing Suite', 'Heritage Archive Displays'],
    directions: 'Central Administrative Building, Main Foyer past the Founder Sir Hari Singh Gour Memorial Statue.',
  },
  {
    id: 'venue-stadium',
    name: 'DHSGSU Sports Complex & Stadium',
    building: 'University Athletic Pavilion',
    floor: 'Ground Level Pavilion',
    capacity: 1200,
    coordinates: { x: 80, y: 18 },
    features: ['400m Athletic Running Track', 'Turf Cricket Pitch', 'Floodlit Pavilion', 'First Aid Station', 'Dressing Rooms'],
    directions: 'South-East Campus ring road past Tagore Boys Hostel.',
  },
  {
    id: 'venue-tagore-mandapam',
    name: 'Rabindranath Tagore Cultural Mandapam',
    building: 'Faculty of Arts & Fine Arts Block',
    floor: 'Ground Floor Amphitheatre',
    capacity: 400,
    coordinates: { x: 44, y: 72 },
    features: ['Proscenium Cultural Stage', 'Green Rooms', 'Stage Lighting Truss', 'Traditional Acoustic Baffles'],
    directions: 'West Campus adjacent to Botanical Gardens and Fine Arts Department.',
  },
  {
    id: 'venue-iic',
    name: 'DHSGSU Innovation & Incubation Centre (IIC)',
    building: 'Central Library Complex (Jawaharlal Nehru Library)',
    floor: 'East Wing, 1st Floor',
    capacity: 110,
    coordinates: { x: 55, y: 65 },
    features: ['Startup Pitch Arena', 'Co-working Pods', 'Prototyping FabLab', 'High-Speed Wi-Fi'],
    directions: 'Enter Jawaharlal Nehru Central Library, take East stairs to Level 1.',
  },
  {
    id: 'venue-law-hall',
    name: 'Pt. Motilal Nehru Moot Court & Law Hall',
    building: 'School of Law & Jurisprudence',
    floor: 'Ground Floor, Room 10',
    capacity: 160,
    coordinates: { x: 22, y: 65 },
    features: ['Simulated High Court Bench', 'Bar Association Gallery', 'Digital Stenography System'],
    directions: 'Law Faculty building, direct entrance from Law Quadrangle.',
  },
];

// Reference date for realistic simulation: today is 2026-09-30
export const INITIAL_EVENTS: CampusEvent[] = [
  {
    _id: 'evt-1',
    title: 'Deep Learning & Computer Vision on Satellite Imagery Workshop',
    description: 'An intensive, hands-on masterclass organized by the Department of Computer Science & Applications (DCSA). Covers PyTorch, convolutional architectures, remote sensing geospatial datasets from Bundelkhand, and real-time edge deployment. Open to all DHSGSU students.',
    category: 'Workshop',
    organizerId: 'org-1',
    organizerName: 'Dr. Alok Sahay',
    organizerEmail: 'alok.sahay@dhsgsu.edu.in',
    venue: 'Turing Advanced Computing Lab (DCSA)',
    venueId: 'venue-dcsa-lab',
    startTime: '2026-09-30T10:00:00Z',
    endTime: '2026-09-30T16:00:00Z',
    capacity: 60,
    registrationCount: 42,
    registrationDeadline: '2026-09-29T23:59:00Z',
    tags: ['AI', 'Computer Vision', 'PyTorch', 'DCSA', 'DHSGSU'],
    coverImage: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
    eligibility: 'Enrolled B.Tech, M.Tech, MCA, and M.Sc students of DHSGSU',
    specialInstructions: 'Bring university identity card and personal laptop with Python 3.11 installed.',
    departmentScope: 'Department of Computer Science & Applications',
    createdAt: '2026-09-10T08:00:00Z',
    updatedAt: '2026-09-25T12:00:00Z',
  },
  {
    _id: 'evt-2',
    title: '78th Gour Memorial National Science & Innovation Symposium',
    description: 'The flagship national science conference honoring the university founder, Sir Dr. Hari Singh Gour. Keynote addresses by leading scientists from ISRO and BARC on advanced nanomaterials, renewable energy, and scientific self-reliance.',
    category: 'Seminar',
    organizerId: 'org-2',
    organizerName: 'Prof. R.K. Trivedi',
    organizerEmail: 'rk.trivedi@dhsgsu.edu.in',
    venue: 'Swarna Jayanti Auditorium',
    venueId: 'venue-swarna-jayanti',
    startTime: '2026-09-30T11:30:00Z',
    endTime: '2026-09-30T15:30:00Z',
    capacity: 500,
    registrationCount: 380,
    registrationDeadline: '2026-09-29T18:00:00Z',
    tags: ['Gour Memorial', 'National Symposium', 'Sciences', 'Keynote', 'DHSGSU'],
    coverImage: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
    eligibility: 'Open to all university students, research scholars, and faculty members',
    specialInstructions: 'Formal university dress code. Seated 15 minutes before the arrival of the Vice-Chancellor.',
    departmentScope: 'Faculty of Science & Academic Council',
    createdAt: '2026-09-01T10:00:00Z',
    updatedAt: '2026-09-28T09:00:00Z',
  },
  {
    _id: 'evt-3',
    title: 'Bundelkhand Folk Heritage & University Youth Festival (Utsav 2026)',
    description: 'An evening celebrating Bundelkhand folk dance (Rai, Badhai), classical ragas, theatrical drama, and instrumental music performed by university cultural troupes across all departments.',
    category: 'Cultural',
    organizerId: 'org-1',
    organizerName: 'Dr. Alok Sahay',
    organizerEmail: 'alok.sahay@dhsgsu.edu.in',
    venue: 'Rabindranath Tagore Cultural Mandapam',
    venueId: 'venue-tagore-mandapam',
    startTime: '2026-10-02T17:00:00Z',
    endTime: '2026-10-02T21:00:00Z',
    capacity: 400,
    registrationCount: 290,
    registrationDeadline: '2026-10-01T23:59:00Z',
    tags: ['Cultural', 'Bundelkhand', 'Music', 'Youth Festival', 'Dance'],
    coverImage: 'https://images.unsplash.com/photo-1469488865564-c2de10f69f96?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
    eligibility: 'All students with valid DHSGSU identity card',
    specialInstructions: 'Digital event pass must be shown at the Tagore Mandapam entrance turnstile.',
    departmentScope: 'University Cultural Affairs Council',
    createdAt: '2026-09-15T11:00:00Z',
    updatedAt: '2026-09-27T16:00:00Z',
  },
  {
    _id: 'evt-4',
    title: 'All-Madhya Pradesh Inter-University Hackathon: Smart Campus & AgriTech',
    description: '36-hour non-stop hackathon organized by DHSGSU Innovation & Incubation Centre. Teams engineer functional software and IoT solutions for rural agriculture, smart energy, and digital campus services.',
    category: 'Coding',
    organizerId: 'org-1',
    organizerName: 'Dr. Alok Sahay',
    organizerEmail: 'alok.sahay@dhsgsu.edu.in',
    venue: 'DHSGSU Innovation & Incubation Centre (IIC)',
    venueId: 'venue-iic',
    startTime: '2026-10-05T09:00:00Z',
    endTime: '2026-10-06T21:00:00Z',
    capacity: 100,
    registrationCount: 78,
    registrationDeadline: '2026-10-03T18:00:00Z',
    tags: ['Hackathon', 'Coding', 'AgriTech', 'IIC', 'Smart Campus'],
    coverImage: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
    eligibility: 'Teams of 2 to 4 enrolled university students',
    specialInstructions: 'Bring extensions, sleeping bags, and personal laptops. Meals provided at Library cafeteria.',
    departmentScope: 'DHSGSU Innovation & Incubation Centre (IIC)',
    createdAt: '2026-09-12T09:30:00Z',
    updatedAt: '2026-09-26T14:20:00Z',
  },
  {
    _id: 'evt-5',
    title: 'Inter-Departmental Cricket Championship & Athletic Trials',
    description: 'Annual inter-departmental sports tournament held at the historic University Stadium on Patharia Hills. Selection trials for West Zone Inter-University tournaments across track, field, and cricket.',
    category: 'Sports',
    organizerId: 'org-2',
    organizerName: 'Prof. R.K. Trivedi',
    organizerEmail: 'rk.trivedi@dhsgsu.edu.in',
    venue: 'DHSGSU Sports Complex & Stadium',
    venueId: 'venue-stadium',
    startTime: '2026-10-08T08:00:00Z',
    endTime: '2026-10-10T18:00:00Z',
    capacity: 600,
    registrationCount: 310,
    registrationDeadline: '2026-10-06T20:00:00Z',
    tags: ['Cricket', 'Athletics', 'Sports', 'University Stadium', 'Trials'],
    coverImage: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
    eligibility: 'Open to registered student athletes representing departmental teams',
    specialInstructions: 'Athletic wear and spiked shoes mandatory. Medical fitness clearance required.',
    departmentScope: 'Department of Physical Education & Sports Board',
    createdAt: '2026-09-18T14:00:00Z',
    updatedAt: '2026-09-28T11:00:00Z',
  },
  {
    _id: 'evt-6',
    title: 'Campus Placement & Corporate Readiness Conclave 2026',
    description: 'Central training and placement drive featuring HR directors and tech leaders from Tata Consultancy Services, Infosys, L&T, and central PSUs. Resume clinics, mock technical interviews, and aptitude orientation.',
    category: 'Placement',
    organizerId: 'org-1',
    organizerName: 'Dr. Alok Sahay',
    organizerEmail: 'alok.sahay@dhsgsu.edu.in',
    venue: 'Swarna Jayanti Auditorium',
    venueId: 'venue-swarna-jayanti',
    startTime: '2026-10-12T09:30:00Z',
    endTime: '2026-10-12T17:00:00Z',
    capacity: 450,
    registrationCount: 420,
    registrationDeadline: '2026-10-10T23:59:00Z',
    tags: ['Placement', 'Career', 'Interviews', 'Corporate', 'Training'],
    coverImage: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
    eligibility: 'Final and Pre-Final Year students of all undergraduate and postgraduate programs',
    specialInstructions: 'Carry 5 copies of your verified university resume and passport photographs in formal attire.',
    departmentScope: 'Central Training & Placement Cell (T&P)',
    createdAt: '2026-09-14T10:00:00Z',
    updatedAt: '2026-09-29T10:30:00Z',
  },
  {
    _id: 'evt-7',
    title: 'Hands-on Workshop: Drone Mapping & Remote Sensing in Bundelkhand',
    description: 'Practical training on geospatial survey drones, multispectral imaging, and GIS mapping for environmental monitoring across the Vindhyan and Patharia hill terrain.',
    category: 'Technology',
    organizerId: 'org-2',
    organizerName: 'Prof. R.K. Trivedi',
    organizerEmail: 'rk.trivedi@dhsgsu.edu.in',
    venue: 'Prof. C.V. Raman Science Lecture Theatre',
    venueId: 'venue-cv-raman',
    startTime: '2026-10-15T10:00:00Z',
    endTime: '2026-10-15T15:30:00Z',
    capacity: 80,
    registrationCount: 65,
    registrationDeadline: '2026-10-13T20:00:00Z',
    tags: ['Drones', 'GIS', 'Remote Sensing', 'Technology', 'Science'],
    coverImage: 'https://images.unsplash.com/photo-1527977966376-1c8408f9f108?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
    eligibility: 'Students of Science, Geography, Geology, and Engineering faculties',
    specialInstructions: 'Field flying demonstration will take place behind Science Block after lunch.',
    departmentScope: 'Department of Applied Geology & Geography',
    createdAt: '2026-09-20T12:00:00Z',
    updatedAt: '2026-09-28T14:00:00Z',
  },
  {
    _id: 'evt-8',
    title: 'Student Venture Pitch & Seed Grant Showcase',
    description: 'Students present early-stage tech, social, and commercial startups before angel investors and alumni venture partners. Top 3 selected teams receive university seed incubation grants of ₹2,50,000.',
    category: 'Entrepreneurship',
    organizerId: 'org-1',
    organizerName: 'Dr. Alok Sahay',
    organizerEmail: 'alok.sahay@dhsgsu.edu.in',
    venue: 'DHSGSU Innovation & Incubation Centre (IIC)',
    venueId: 'venue-iic',
    startTime: '2026-10-18T10:00:00Z',
    endTime: '2026-10-18T16:00:00Z',
    capacity: 100,
    registrationCount: 52,
    registrationDeadline: '2026-10-16T18:00:00Z',
    tags: ['Startup', 'Pitch', 'Grants', 'Incubation', 'Entrepreneurship'],
    coverImage: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
    eligibility: 'Any enrolled student or multidisciplinary team with an innovative pitch deck',
    specialInstructions: 'Pitches limited strictly to 7 minutes followed by 5 minutes Q&A.',
    departmentScope: 'DHSGSU Innovation & Incubation Centre',
    createdAt: '2026-09-21T09:00:00Z',
    updatedAt: '2026-09-29T11:00:00Z',
  },
  {
    _id: 'evt-9',
    title: 'National Moot Court Competition: Constitutional Law in the Digital Age',
    description: 'Prestigious national moot court competition focusing on constitutional privacy rights, surveillance regulation, and fundamental liberties in modern digital societies.',
    category: 'Competition',
    organizerId: 'org-2',
    organizerName: 'Prof. R.K. Trivedi',
    organizerEmail: 'rk.trivedi@dhsgsu.edu.in',
    venue: 'Pt. Motilal Nehru Moot Court & Law Hall',
    venueId: 'venue-law-hall',
    startTime: '2026-10-22T09:00:00Z',
    endTime: '2026-10-23T18:00:00Z',
    capacity: 120,
    registrationCount: 94,
    registrationDeadline: '2026-10-19T23:59:00Z',
    tags: ['Moot Court', 'Law', 'Constitution', 'Competition', 'DHSGSU'],
    coverImage: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
    eligibility: 'LL.B and B.A. LL.B student teams',
    specialInstructions: 'Advocate robes mandatory for oral arguments. Memorial submission due 48 hours prior.',
    departmentScope: 'School of Law & Jurisprudence',
    createdAt: '2026-09-22T10:00:00Z',
    updatedAt: '2026-09-29T13:00:00Z',
  },
  {
    _id: 'evt-10',
    title: 'University Astronomy Night: Planetary Observation from Patharia Hills',
    description: 'Public observation of Jupiter, Saturn’s rings, and deep-sky nebulae utilizing the Department of Physics 12-inch Cassegrain telescope on the clear summit of Patharia Hills.',
    category: 'Club',
    organizerId: 'org-1',
    organizerName: 'Dr. Alok Sahay',
    organizerEmail: 'alok.sahay@dhsgsu.edu.in',
    venue: 'Prof. C.V. Raman Science Lecture Theatre',
    venueId: 'venue-cv-raman',
    startTime: '2026-10-25T19:00:00Z',
    endTime: '2026-10-25T22:30:00Z',
    capacity: 150,
    registrationCount: 110,
    registrationDeadline: '2026-10-24T18:00:00Z',
    tags: ['Astronomy', 'Telescope', 'Night Sky', 'Club', 'Patharia Hills'],
    coverImage: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
    eligibility: 'Open to all students, university families, and stargazing enthusiasts',
    specialInstructions: 'Warm clothing recommended for evening terrace winds on the hill.',
    departmentScope: 'DHSGSU Amateur Astronomy Club',
    createdAt: '2026-09-23T11:00:00Z',
    updatedAt: '2026-09-29T15:00:00Z',
  },
  {
    _id: 'evt-11',
    title: 'Human-Centered Design & Interactive Systems Workshop',
    description: 'A 2-day hands-on studio on information architecture, micro-interactions, and accessibility standards for modern campus digital tools. Led by visiting design researchers.',
    category: 'Academic',
    organizerId: 'org-1',
    organizerName: 'Dr. Alok Sahay',
    organizerEmail: 'alok.sahay@dhsgsu.edu.in',
    venue: 'Turing Advanced Computing Lab (DCSA)',
    venueId: 'venue-dcsa-lab',
    startTime: '2026-10-28T10:00:00Z',
    endTime: '2026-10-29T16:00:00Z',
    capacity: 45,
    registrationCount: 38,
    registrationDeadline: '2026-10-26T20:00:00Z',
    tags: ['Design', 'UI/UX', 'Accessibility', 'Academic', 'DCSA'],
    coverImage: 'https://images.unsplash.com/photo-1581291518655-9523c932edcf?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
    eligibility: 'All students interested in software interface engineering and ergonomics',
    specialInstructions: 'Sketchbooks and digital wireframing tools will be supplied.',
    departmentScope: 'Department of Computer Science & Applications',
    createdAt: '2026-09-24T14:00:00Z',
    updatedAt: '2026-09-29T16:00:00Z',
  },
  {
    _id: 'evt-12',
    title: 'Annual Hindi & Bundeli Sahitya Sabha: Heritage Poetry and Dialogue',
    description: 'Renowned writers and student poets convene in Gour Bhavan Senate Hall to celebrate the literary tradition of Bundelkhand, featuring poetry recitations and panel discussions on regional storytelling.',
    category: 'Other',
    organizerId: 'org-2',
    organizerName: 'Prof. R.K. Trivedi',
    organizerEmail: 'rk.trivedi@dhsgsu.edu.in',
    venue: 'Gour Bhavan Senate & Conference Hall',
    venueId: 'venue-gour-bhavan',
    startTime: '2026-11-01T14:00:00Z',
    endTime: '2026-11-01T18:00:00Z',
    capacity: 150,
    registrationCount: 88,
    registrationDeadline: '2026-10-30T18:00:00Z',
    tags: ['Literature', 'Hindi', 'Bundelkhand', 'Poetry', 'Heritage'],
    coverImage: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
    eligibility: 'Open to all university community members',
    specialInstructions: 'Students wishing to recite original poetry must register at the podium by 1:30 PM.',
    departmentScope: 'Department of Hindi & Indian Languages',
    createdAt: '2026-09-25T10:00:00Z',
    updatedAt: '2026-09-29T17:00:00Z',
  }
];

export const INITIAL_REGISTRATIONS: Registration[] = [
  {
    _id: 'reg-1',
    eventId: 'evt-1',
    userId: 'student-1',
    userName: 'Amit Sharma',
    userRollNumber: 'Y23141042',
    userDepartment: 'Department of Computer Science & Applications',
    userEmail: 'amit.sharma@dhsgsu.edu.in',
    status: 'CONFIRMED',
    registeredAt: '2026-09-20T14:30:00Z',
    qrToken: 'PARISAR-PASS-DL-CS042',
    checkedInAt: null,
  },
  {
    _id: 'reg-2',
    eventId: 'evt-2',
    userId: 'student-1',
    userName: 'Amit Sharma',
    userRollNumber: 'Y23141042',
    userDepartment: 'Department of Computer Science & Applications',
    userEmail: 'amit.sharma@dhsgsu.edu.in',
    status: 'CONFIRMED',
    registeredAt: '2026-09-22T09:15:00Z',
    qrToken: 'PARISAR-PASS-GM-CS042',
    checkedInAt: null,
  },
  {
    _id: 'reg-3',
    eventId: 'evt-3',
    userId: 'student-2',
    userName: 'Priya Patel',
    userRollNumber: 'Y23122018',
    userDepartment: 'Department of Electronics & Communication',
    userEmail: 'priya.patel@dhsgsu.edu.in',
    status: 'CONFIRMED',
    registeredAt: '2026-09-21T16:00:00Z',
    qrToken: 'PARISAR-PASS-UT-EC118',
    checkedInAt: '2026-09-30T09:12:00Z',
  },
  {
    _id: 'reg-4',
    eventId: 'evt-1',
    userId: 'student-3',
    userName: 'Rohan Mehra',
    userRollNumber: 'Y23141088',
    userDepartment: 'Department of Computer Science & Applications',
    userEmail: 'rohan.mehra@dhsgsu.edu.in',
    status: 'CONFIRMED',
    registeredAt: '2026-09-20T15:00:00Z',
    qrToken: 'PARISAR-PASS-DL-CS088',
    checkedInAt: '2026-09-30T08:45:00Z',
  }
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    _id: 'att-1',
    eventId: 'evt-1',
    registrationId: 'reg-4',
    userId: 'student-3',
    userName: 'Rohan Mehra',
    userRollNumber: 'Y23141088',
    userDepartment: 'Department of Computer Science & Applications',
    checkedInAt: '2026-09-30T08:45:00Z',
    checkedInBy: 'org-1',
    method: 'qr',
  },
  {
    _id: 'att-2',
    eventId: 'evt-3',
    registrationId: 'reg-3',
    userId: 'student-2',
    userName: 'Priya Patel',
    userRollNumber: 'Y23122018',
    userDepartment: 'Department of Electronics & Communication',
    checkedInAt: '2026-09-30T09:12:00Z',
    checkedInBy: 'org-1',
    method: 'qr',
  }
];

export const INITIAL_CERTIFICATES: Certificate[] = [
  {
    _id: 'cert-1',
    eventId: 'evt-past-1',
    eventTitle: 'National Workshop on High-Performance Distributed Computing',
    userId: 'student-1',
    userName: 'Amit Sharma',
    userRollNumber: 'Y23141042',
    department: 'Department of Computer Science & Applications',
    certificateUrl: '/certificates/cert-hp-dc-042.pdf',
    verificationCode: 'DHSGSU-CERT-2026-CS8841',
    issuedAt: '2026-08-28T16:00:00Z',
    certificateType: 'EXCELLENCE',
    issueAuthorizedBy: 'Dr. Alok Sahay, Faculty Convener',
    academicAuthority: "Office of the Dean of Students' Welfare (DSW), DHSGSU",
  },
  {
    _id: 'cert-2',
    eventId: 'evt-past-2',
    eventTitle: 'Inter-University Bundelkhand Science Hackathon 2025',
    userId: 'student-1',
    userName: 'Amit Sharma',
    userRollNumber: 'Y23141042',
    department: 'Department of Computer Science & Applications',
    certificateUrl: '/certificates/cert-hack-042.pdf',
    verificationCode: 'DHSGSU-CERT-2025-HK3319',
    issuedAt: '2025-11-15T18:00:00Z',
    certificateType: 'MERIT',
    issueAuthorizedBy: 'Prof. R.K. Trivedi, Organizing Secretary',
    academicAuthority: "Office of the Dean of Students' Welfare (DSW), DHSGSU",
  }
];

export const INITIAL_NOTIFICATIONS: CampusNotification[] = [
  {
    _id: 'notif-1',
    userId: 'student-1',
    eventId: 'evt-1',
    type: 'REGISTRATION_CONFIRMED',
    title: 'Registration Confirmed: Deep Learning Workshop',
    message: 'Your seat in the Turing Advanced Computing Lab (DCSA) is locked. Your PARISAR digital pass is ready for door check-in.',
    read: false,
    createdAt: '2026-09-29T14:30:00Z',
  },
  {
    _id: 'notif-2',
    userId: 'student-1',
    eventId: 'evt-1',
    type: 'VENUE_CHANGED',
    title: 'Laboratory Preparation Notice',
    message: 'Please ensure PyTorch and Python 3.11 are installed on your personal laptops before entering the DCSA Turing Lab.',
    read: false,
    createdAt: '2026-09-30T07:15:00Z',
  },
  {
    _id: 'notif-3',
    userId: 'student-1',
    eventId: 'evt-2',
    type: 'EVENT_REMINDER',
    title: 'Event Today: 78th Gour Memorial Symposium',
    message: 'Starting at 11:30 AM in Swarna Jayanti Auditorium. Please arrive 15 minutes before the academic procession begins.',
    read: true,
    createdAt: '2026-09-30T06:00:00Z',
  }
];

export const INITIAL_ACHIEVEMENTS: AchievementBadge[] = [
  {
    id: 'ach-1',
    name: 'DHSGSU Campus Explorer',
    description: 'Participated in university events across 3 distinct academic faculties on Patharia Hills.',
    iconName: 'Compass',
    category: 'Exploration',
    unlockedAt: '2026-08-28T16:00:00Z',
    progress: 3,
    total: 3,
  },
  {
    id: 'ach-2',
    name: 'Advanced Computing Scholar',
    description: 'Successfully completed 30+ verified lab workshop hours organized by DCSA.',
    iconName: 'Cpu',
    category: 'Workshops',
    unlockedAt: '2026-09-15T12:00:00Z',
    progress: 30,
    total: 30,
  },
  {
    id: 'ach-3',
    name: 'Gour Memorial Honoree',
    description: 'Attended the prestigious annual university founder commemoration symposium.',
    iconName: 'Award',
    category: 'Academic',
    progress: 2,
    total: 3,
  },
  {
    id: 'ach-4',
    name: 'Hackathon Contender',
    description: 'Engineered a working software prototype during an inter-university coding competition.',
    iconName: 'Zap',
    category: 'Coding',
    unlockedAt: '2025-11-15T18:00:00Z',
    progress: 1,
    total: 1,
  }
];

export const PASSPORT_ACHIEVEMENTS = INITIAL_ACHIEVEMENTS;

export const INITIAL_FEEDBACK: EventFeedback[] = [
  {
    _id: 'fb-1',
    eventId: 'evt-past-1',
    userId: 'student-1',
    userName: 'Amit Sharma',
    rating: 5,
    comment: 'Exceptional hands-on training in the DCSA lab. The practical GPU pipelines were immediately applicable.',
    createdAt: '2026-08-29T10:00:00Z',
  },
  {
    _id: 'fb-2',
    eventId: 'evt-past-1',
    userId: 'student-2',
    userName: 'Priya Patel',
    rating: 5,
    comment: 'Clear explanations and excellent faculty mentoring from Dr. Alok Sahay.',
    createdAt: '2026-08-29T11:30:00Z',
  }
];
