import { 
  User, 
  CampusEvent, 
  CampusVenue, 
  Registration, 
  AttendanceRecord, 
  Certificate, 
  CampusNotification, 
  EventFeedback,
  AchievementBadge
} from '../types';

export const INITIAL_USERS: User[] = [
  {
    _id: 'student-amit-y25170504',
    name: 'Amit Sharma',
    email: 'y25170504@dhsgsu.edu.in',
    passwordHash: 'Programmer@01',
    rollNumber: 'Y25170504',
    department: 'Department of Computer Science & Applications (DCSA)',
    semester: 2,
    role: 'student',
    organizerStatus: 'NONE',
    interests: ['Technology', 'Coding', 'Entrepreneurship', 'Workshop'],
    profileImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
    phone: '+91 98260 12345',
    createdAt: '2026-09-30T10:00:00Z',
    updatedAt: '2026-09-30T10:00:00Z',
  },
  {
    _id: 'student-1',
    name: 'Amit Sharma',
    email: 'amit.sharma@dhsgsu.edu.in',
    rollNumber: 'Y23141042',
    department: 'Department of Computer Science & Applications',
    semester: 6,
    role: 'student',
    organizerStatus: 'NONE',
    interests: ['Technology', 'Coding', 'Entrepreneurship', 'Workshop'],
    profileImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
    phone: '+91 98260 12345',
    createdAt: '2025-08-01T09:00:00Z',
    updatedAt: '2026-03-15T11:20:00Z',
  },
  {
    _id: 'student-2',
    name: 'Priya Patel',
    email: 'priya.patel@dhsgsu.edu.in',
    rollNumber: 'Y23122018',
    department: 'Department of Electronics & Communication',
    semester: 4,
    role: 'organizer',
    organizerStatus: 'PENDING',
    designation: 'B.Tech Student & Electronics Society Secretary',
    organization: 'DHSGSU Electronics Society',
    interests: ['Cultural', 'Sports', 'Seminar', 'Workshop'],
    profileImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=250&q=80',
    phone: '+91 98260 67890',
    createdAt: '2025-08-10T10:00:00Z',
    updatedAt: '2026-02-18T14:10:00Z',
  },
  {
    _id: 'student-3',
    name: 'Rohan Mehra',
    email: 'rohan.mehra@dhsgsu.edu.in',
    rollNumber: 'Y23141088',
    department: 'Department of Computer Science & Applications',
    semester: 6,
    role: 'organizer',
    organizerStatus: 'REJECTED',
    designation: 'M.Sc Student & Open Source Club Lead',
    organization: 'DHSGSU Open Source Initiative',
    interests: ['Coding', 'Competition', 'Technology'],
    profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80',
    phone: '+91 94250 11223',
    createdAt: '2025-08-05T09:00:00Z',
    updatedAt: '2026-02-20T10:00:00Z',
  },
  {
    _id: 'org-1',
    name: 'Dr. Alok Sahay',
    email: 'alok.sahay@dhsgsu.edu.in',
    rollNumber: 'EMP-DCSA-104',
    department: 'Department of Computer Science & Applications (DCSA)',
    role: 'organizer',
    organizerStatus: 'VERIFIED',
    designation: 'Associate Professor & Faculty Convener',
    organization: 'DHSGSU Centre for Computing & Innovation',
    interests: ['Technology', 'Coding', 'Workshop', 'Seminar'],
    profileImage: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=250&q=80',
    phone: '+91 75822 64201',
    createdAt: '2024-06-01T09:00:00Z',
    updatedAt: '2026-01-10T09:00:00Z',
  },
  {
    _id: 'org-2',
    name: 'Prof. R.K. Trivedi',
    email: 'rk.trivedi@dhsgsu.edu.in',
    rollNumber: 'EMP-FET-201',
    department: 'Department of Technology & Engineering',
    role: 'organizer',
    organizerStatus: 'VERIFIED',
    designation: 'Professor & Dean, Faculty of Engineering & Technology',
    organization: 'DHSGSU Robotics & Automation Council',
    interests: ['Competition', 'Workshop', 'Sports'],
    profileImage: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=250&q=80',
    phone: '+91 75822 64205',
    createdAt: '2024-07-15T09:00:00Z',
    updatedAt: '2026-02-12T10:00:00Z',
  },
  {
    _id: 'admin-1',
    name: 'Prof. S.P. Gautam',
    email: 'dsw@dhsgsu.edu.in',
    rollNumber: 'ADMIN-DSW-001',
    department: "Office of the Dean of Students' Welfare (DSW)",
    role: 'admin',
    organizerStatus: 'VERIFIED',
    designation: "Dean of Students' Welfare & Proctor",
    organization: 'Dr. Harisingh Gour Vishwavidyalaya, Sagar (M.P.)',
    interests: ['Academic', 'Administration', 'Governance'],
    profileImage: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=250&q=80',
    phone: '+91 75822 64400',
    createdAt: '2023-01-01T09:00:00Z',
    updatedAt: '2026-01-01T09:00:00Z',
  }
];

export const INITIAL_ORGANIZER_REQUESTS: import('../types').OrganizerVerificationRequest[] = [
  {
    id: 'req-01',
    userId: 'student-2',
    fullName: 'Priya Patel',
    universityId: 'Y23122018',
    department: 'Department of Electronics & Communication',
    designation: 'B.Tech Student & Electronics Society Secretary',
    email: 'priya.patel@dhsgsu.edu.in',
    phone: '+91 98260 67890',
    reason: 'Requesting permission to organize the Annual VLSI & Embedded Systems Workshop for undergraduate engineering students in Raman Theatre.',
    status: 'PENDING',
    submittedAt: '2026-09-28T14:30:00Z',
  },
  {
    id: 'req-02',
    userId: 'student-3',
    fullName: 'Rohan Mehra',
    universityId: 'Y23141088',
    department: 'Department of Computer Science & Applications',
    designation: 'M.Sc Student & Open Source Club Lead',
    email: 'rohan.mehra@dhsgsu.edu.in',
    phone: '+91 94250 11223',
    reason: 'Organizing an independent late-night gaming tournament in the computing lab without faculty faculty advisor endorsement.',
    status: 'REJECTED',
    submittedAt: '2026-09-25T10:15:00Z',
    reviewedAt: '2026-09-26T16:20:00Z',
    reviewRemarks: 'Requires formal endorsement letter from Head of Department (DCSA) and a designated faculty convener.',
  },
  {
    id: 'req-03',
    userId: 'org-1',
    fullName: 'Dr. Alok Sahay',
    universityId: 'EMP-DCSA-104',
    department: 'Department of Computer Science & Applications (DCSA)',
    designation: 'Associate Professor & Faculty Convener',
    email: 'alok.sahay@dhsgsu.edu.in',
    phone: '+91 75822 64201',
    reason: 'Faculty Convener for Departmental Seminars, ACM Student Chapter, and National Computing Studios.',
    status: 'APPROVED',
    submittedAt: '2025-06-01T09:00:00Z',
    reviewedAt: '2025-06-02T11:00:00Z',
    reviewRemarks: 'Verified faculty credentials by Dean of Students Welfare Office.',
  }
];

export const DHSGSU_CAMPUS_CENTER = {
  name: 'Dr. Harisingh Gour Vishwavidyalaya (Central University)',
  address: 'Patharia Hills, Gour Nagar, University Road, Sagar, Madhya Pradesh 470003, India',
  latitude: 23.8266315,
  longitude: 78.7712846,
  defaultZoom: 16,
};

export const CAMPUS_VENUES: CampusVenue[] = [
  // ============================================================================
  // 1. VERIFIED EXACT GIS COORDINATES (OpenStreetMap + Official DHSGSU Records)
  // ============================================================================
  {
    id: 'venue-central-library',
    name: 'Jawaharlal Nehru Central Library',
    category: 'Library',
    latitude: 23.8266315,
    longitude: 78.7712846,
    description: 'Central University Library on Patharia Hills housing academic collections, digital repository access, and reading halls.',
    address: 'Main Academic Ridge, Patharia Hills, DHSGSU, Sagar, MP 470003',
    verified: 'verified',
    source: 'OpenStreetMap node/9406704917 & Official DHSGSU Library Portal (Tel: 07582-265605)',
    navigationQuery: '23.8266315,78.7712846',
    isEventVenue: true,
    building: 'Jawaharlal Nehru Central Library Building',
  },
  {
    id: 'venue-gour-bhavan',
    name: 'Administrative Building (Gour Samiti Kaksh)',
    category: 'Administration',
    latitude: 23.8269023,
    longitude: 78.7711252,
    description: 'Central University Administrative Office, Vice-Chancellor Secretariat, Registrar Office, and Gour Samiti Kaksh conference hall.',
    address: 'Central Administrative Block, Patharia Hills, DHSGSU, Sagar, MP 470003',
    verified: 'verified',
    source: 'OpenStreetMap node/8174357902 & Official DHSGSU Administration Records',
    navigationQuery: '23.8269023,78.7711252',
    isEventVenue: true,
    building: 'Central Administrative Building, Patharia Hills',
  },
  {
    id: 'venue-geography-dept',
    name: 'Department of General & Applied Geography',
    category: 'Academic',
    latitude: 23.8280972,
    longitude: 78.7723024,
    description: 'Academic department under the School of Applied Sciences conducting GIS, remote sensing, and earth science seminars and workshops.',
    address: 'North Academic Ridge, Patharia Hills, DHSGSU, Sagar, MP 470003',
    verified: 'verified',
    source: 'OpenStreetMap node/8174413178 (Operator: Dr. H.S. Gour Central University)',
    navigationQuery: '23.8280972,78.7723024',
    isEventVenue: true,
    building: 'Department of General & Applied Geography',
  },
  {
    id: 'venue-law-hall',
    name: 'Department of Law',
    category: 'Academic',
    latitude: 23.8247728,
    longitude: 78.7713512,
    description: 'School of Law academic block hosting legal aid clinics, constitutional seminars, and university moot court sessions.',
    address: 'Law Faculty Block, Patharia Hills, DHSGSU, Sagar, MP 470003',
    verified: 'verified',
    source: 'OpenStreetMap node/9406693317 (http://www.dhsgsu.edu.in, Postcode 470003)',
    navigationQuery: '23.8247728,78.7713512',
    isEventVenue: true,
    building: 'School of Law, Patharia Hills',
  },
  {
    id: 'dept-criminology',
    name: 'Department of Criminology & Forensic Science (Valley Campus)',
    category: 'Academic',
    latitude: 23.8242985,
    longitude: 78.7828413,
    description: 'Department of Criminology & Forensic Science located on Criminology Department Road in the DHSGSU Valley Campus sector.',
    address: 'Criminology Department Road, Valley Campus, DHSGSU, Sagar, MP 470003',
    verified: 'verified',
    source: 'OpenStreetMap way/1563496960 (Criminology Department Road) & Official DHSGSU Directory',
    navigationQuery: '23.8242985,78.7828413',
    isEventVenue: true,
    building: 'Valley Campus Academic Block',
  },
  {
    id: 'acharya-shankar-bhawan',
    name: 'Aacharya Shankar Bhawan',
    category: 'Academic',
    latitude: 23.8244744,
    longitude: 78.7719758,
    description: 'Academic humanities and philosophy building on the central Patharia Hills campus.',
    address: 'Patharia Hills, Gour Nagar, DHSGSU, Sagar, MP 470003',
    verified: 'verified',
    source: 'OpenStreetMap node/11962713956 (DHSGSU Campus, Sagar)',
    navigationQuery: '23.8244744,78.7719758',
    isEventVenue: true,
    building: 'Aacharya Shankar Bhawan',
  },
  {
    id: 'university-hospital',
    name: 'University Hospital / Health Centre',
    category: 'Medical',
    latitude: 23.8240947,
    longitude: 78.7745534,
    description: 'Dr. Harisingh Gour Central University Hospital & Health Centre providing medical care and emergency support for students and staff.',
    address: 'Hospital Road, Gour Nagar, DHSGSU, Sagar, MP 470003',
    verified: 'verified',
    source: 'OpenStreetMap node/7518423177 (Tel: +91 7582 264287)',
    navigationQuery: '23.8240947,78.7745534',
    isEventVenue: false,
    building: 'University Health Centre',
  },
  {
    id: 'university-guest-house',
    name: 'University Guest House',
    category: 'Administration',
    latitude: 23.8256768,
    longitude: 78.7720488,
    description: 'Official University Guest House & Visitors House accommodating visiting academicians, conference keynote speakers, and examination panels.',
    address: 'Gour Nagar, Patharia Hills, DHSGSU, Sagar, MP 470003',
    verified: 'verified',
    source: 'OpenStreetMap node/11962731169 (Postcode 470003)',
    navigationQuery: '23.8256768,78.7720488',
    isEventVenue: false,
    building: 'University Guest House',
  },
  {
    id: 'hostel-tagore',
    name: 'Tagore Hostel',
    category: 'Hostel',
    latitude: 23.8214984,
    longitude: 78.7713000,
    description: 'University residential student hostel on the southern residential ridge of Patharia Hills.',
    address: 'South Residential Sector, Patharia Hills, DHSGSU, Sagar, MP 470003',
    verified: 'verified',
    source: 'OpenStreetMap node/8174386332 (Operator: Dr. H.S. Gour Central University)',
    navigationQuery: '23.8214984,78.7713000',
    isEventVenue: false,
    building: 'Tagore Boys Hostel',
  },
  {
    id: 'hostel-vivekanand',
    name: 'Vivekanand Hostel',
    category: 'Hostel',
    latitude: 23.8206889,
    longitude: 78.7701816,
    description: 'University student residential hostel operated by Dr. Harisingh Gour Vishwavidyalaya.',
    address: 'South Residential Sector, Patharia Hills, DHSGSU, Sagar, MP 470003',
    verified: 'verified',
    source: 'OpenStreetMap node/8174386331 (Operator: Dr. H.S. Gour Central University)',
    navigationQuery: '23.8206889,78.7701816',
    isEventVenue: false,
    building: 'Vivekanand Hostel',
  },
  {
    id: 'hostel-international',
    name: 'International Boys Hostel DHSGSU',
    category: 'Hostel',
    latitude: 23.8221420,
    longitude: 78.7723501,
    description: 'University residential hostel complex for international and postgraduate scholars at DHSGSU.',
    address: 'Residential Zone, Patharia Hills, DHSGSU, Sagar, MP 470003',
    verified: 'verified',
    source: 'OpenStreetMap node/9406688617',
    navigationQuery: '23.8221420,78.7723501',
    isEventVenue: false,
    building: 'International Boys Hostel',
  },
  {
    id: 'hostel-raman',
    name: 'Raman Hostel',
    category: 'Hostel',
    latitude: 23.8183427,
    longitude: 78.7673139,
    description: 'Sir C.V. Raman residential student hostel on the southwest Patharia Hills sector.',
    address: 'Southwest Hostel Road, Patharia Hills, DHSGSU, Sagar, MP 470003',
    verified: 'verified',
    source: 'OpenStreetMap node/11962749603',
    navigationQuery: '23.8183427,78.7673139',
    isEventVenue: false,
    building: 'Raman Hostel',
  },
  {
    id: 'hostel-bhabha',
    name: 'Bhabha Hostel',
    category: 'Hostel',
    latitude: 23.8174879,
    longitude: 78.7664711,
    description: 'Homi Jehangir Bhabha student residential hostel on the southern campus boundary.',
    address: 'Southwest Hostel Sector, Patharia Hills, DHSGSU, Sagar, MP 470003',
    verified: 'verified',
    source: 'OpenStreetMap node/11962704604 (Postcode 470003)',
    navigationQuery: '23.8174879,78.7664711',
    isEventVenue: false,
    building: 'Bhabha Hostel',
  },
  {
    id: 'indian-coffee-house',
    name: 'Indian Coffee House (University Road)',
    category: 'Food',
    latitude: 23.8298237,
    longitude: 78.7745052,
    description: 'Campus dining landmark along University Road near the north entrance to Patharia Hills.',
    address: 'University Road, Gour Nagar, Sagar, MP 470003',
    verified: 'verified',
    source: 'OpenStreetMap node/11962765981 (Postcode 470003)',
    navigationQuery: '23.8298237,78.7745052',
    isEventVenue: false,
    building: 'University Road Campus Approach',
  },

  // ============================================================================
  // 2. PARTIALLY VERIFIED CAMPUS SECTOR LOCATIONS (Official DHSGSU Venues mapped to verified campus sector)
  // ============================================================================
  {
    id: 'venue-swarna-jayanti',
    name: 'Swarn Jayanti Hall (Golden Jubilee Auditorium)',
    category: 'Event Venue',
    latitude: 23.8264500,
    longitude: 78.7716500,
    description: 'Primary university convocation, national symposium, admission counselling, and placement auditorium on the Main Academic Ridge.',
    address: 'Main Academic Ridge, near Central Library, Patharia Hills, DHSGSU, Sagar, MP 470003',
    verified: 'partially_verified',
    source: 'Official DHSGSU Convocation & Counselling Notices (Sector coordinate near Central Library & Administrative Block)',
    navigationQuery: 'Swarn Jayanti Hall Dr Harisingh Gour Vishwavidyalaya Sagar',
    isEventVenue: true,
    building: 'Golden Jubilee Auditorium Complex, Patharia Hills',
  },
  {
    id: 'venue-abhimanch',
    name: 'Abhimanch Sabhagar (University Auditorium)',
    category: 'Event Venue',
    latitude: 23.8259500,
    longitude: 78.7714500,
    description: 'University auditorium and cultural venue used for youth festivals, theatrical performances, and inter-departmental cultural gatherings.',
    address: 'Central Campus Sector, Patharia Hills, DHSGSU, Sagar, MP 470003',
    verified: 'partially_verified',
    source: 'Official DHSGSU Cultural & Conference Notices (Central Campus Sector coordinate)',
    navigationQuery: 'Dr Harisingh Gour Vishwavidyalaya Auditorium Sagar',
    isEventVenue: true,
    building: 'Central Campus Auditorium Sector',
  },
  {
    id: 'venue-dcsa-lab',
    name: 'Department of Computer Science & Applications (DCSA)',
    category: 'Academic',
    latitude: 23.8273619,
    longitude: 78.7712719,
    description: 'Academic department under the School of Mathematical & Physical Sciences hosting computing workshops, coding labs, and technical seminars.',
    address: 'Academic Ridge, Patharia Hills, DHSGSU, Sagar, MP 470003',
    verified: 'partially_verified',
    source: 'Official DHSGSU School of Mathematical & Physical Sciences Directory & OSM Campus Building Way 968094446',
    navigationQuery: 'Department of Computer Science and Applications Dr Harisingh Gour University Sagar',
    isEventVenue: true,
    building: 'School of Mathematical & Physical Sciences (DCSA)',
  },
  {
    id: 'venue-stadium',
    name: 'University Sports Ground & Stadium',
    category: 'Sports',
    latitude: 23.8232000,
    longitude: 78.7711000,
    description: 'University outdoor athletics ground and sports pavilion managed by the Directorate of Physical Education & Sports.',
    address: 'Sports Sector, Patharia Hills, DHSGSU, Sagar, MP 470003',
    verified: 'partially_verified',
    source: 'Official DHSGSU Directorate of Physical Education & Sports (Campus Sports Sector coordinate)',
    navigationQuery: 'University Sports Ground Dr Harisingh Gour University Sagar',
    isEventVenue: true,
    building: 'Directorate of Physical Education & Sports',
  },

  // ============================================================================
  // 3. UNVERIFIED EXACT COORDINATES (Official DHSGSU Departments without individual public GIS pin)
  // Searchable in directory & linked to Google Maps query without placing fabricated pins
  // ============================================================================
  {
    id: 'dept-pharmacy',
    name: 'Department of Pharmaceutical Sciences',
    category: 'Academic',
    latitude: null,
    longitude: null,
    description: 'Premier pharmaceutical education and research department under the School of Engineering & Technology at DHSGSU.',
    address: 'Patharia Hills Campus, DHSGSU, Sagar, MP 470003',
    verified: 'unverified',
    source: 'Official DHSGSU Academic Departments Directory (Exact building coordinate not individually indexed in public GIS)',
    navigationQuery: 'Department of Pharmaceutical Sciences Dr Harisingh Gour University Sagar',
    isEventVenue: true,
    building: 'Department of Pharmaceutical Sciences',
  },
  {
    id: 'dept-physics',
    name: 'Department of Physics',
    category: 'Academic',
    latitude: null,
    longitude: null,
    description: 'Department of Physics under the School of Mathematical & Physical Sciences at Dr. Harisingh Gour Vishwavidyalaya.',
    address: 'Science Block, Patharia Hills, DHSGSU, Sagar, MP 470003',
    verified: 'unverified',
    source: 'Official DHSGSU Academic Departments Directory (Exact building coordinate not individually indexed in public GIS)',
    navigationQuery: 'Department of Physics Dr Harisingh Gour University Sagar',
    isEventVenue: true,
    building: 'School of Mathematical & Physical Sciences',
  },
  {
    id: 'dept-chemistry',
    name: 'Department of Chemistry',
    category: 'Academic',
    latitude: null,
    longitude: null,
    description: 'Department of Chemistry under the School of Chemical Sciences & Technology at DHSGSU.',
    address: 'Science Block, Patharia Hills, DHSGSU, Sagar, MP 470003',
    verified: 'unverified',
    source: 'Official DHSGSU Academic Departments Directory (Exact building coordinate not individually indexed in public GIS)',
    navigationQuery: 'Department of Chemistry Dr Harisingh Gour University Sagar',
    isEventVenue: true,
    building: 'School of Chemical Sciences & Technology',
  },
  {
    id: 'dept-botany',
    name: 'Department of Botany & Microbiology',
    category: 'Academic',
    latitude: null,
    longitude: null,
    description: 'Department of Botany & Microbiology under the School of Biological & Chemical Sciences.',
    address: 'Biological Sciences Sector, Patharia Hills, DHSGSU, Sagar, MP 470003',
    verified: 'unverified',
    source: 'Official DHSGSU Academic Departments Directory (Exact building coordinate not individually indexed in public GIS)',
    navigationQuery: 'Department of Botany Dr Harisingh Gour University Sagar',
    isEventVenue: false,
    building: 'School of Biological & Chemical Sciences',
  },
  {
    id: 'dept-commerce',
    name: 'Department of Commerce & Business Management',
    category: 'Academic',
    latitude: null,
    longitude: null,
    description: 'School of Commerce & Business Management hosting management seminars, entrepreneurship lectures, and commerce workshops.',
    address: 'Patharia Hills Campus, DHSGSU, Sagar, MP 470003',
    verified: 'unverified',
    source: 'Official DHSGSU Academic Departments Directory (Exact building coordinate not individually indexed in public GIS)',
    navigationQuery: 'Department of Commerce Dr Harisingh Gour University Sagar',
    isEventVenue: true,
    building: 'School of Commerce & Business Management',
  },
];

// Reference date for realistic simulation: today is 2026-09-30
export const INITIAL_EVENTS: CampusEvent[] = [
  {
    _id: 'evt-1',
    title: 'Deep Learning & Computer Vision on Satellite Imagery Workshop',
    description: 'An intensive, hands-on masterclass organized by the Department of Computer Science & Applications (DCSA). Covers PyTorch, convolutional architectures, remote sensing geospatial datasets from Bundelkhand, and real-time edge deployment. Open to all DHSGSU students.',
    category: 'Workshop',
    organizerId: 'org-1',
    organizerName: 'Dr. Alok Sahay',
    organizerEmail: 'alok.sahay@dhsgsu.edu.in',
    venue: 'Department of Computer Science & Applications (DCSA)',
    venueId: 'venue-dcsa-lab',
    startTime: '2026-09-30T10:00:00Z',
    endTime: '2026-09-30T16:00:00Z',
    capacity: 60,
    registrationCount: 42,
    registrationDeadline: '2026-09-29T23:59:00Z',
    tags: ['AI', 'Computer Vision', 'PyTorch', 'DCSA', 'DHSGSU'],
    coverImage: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
    eligibility: 'Enrolled B.Tech, M.Tech, MCA, and M.Sc students of DHSGSU',
    specialInstructions: 'Bring university identity card and personal laptop with Python 3.11 installed.',
    departmentScope: 'Department of Computer Science & Applications',
    createdAt: '2026-09-10T08:00:00Z',
    updatedAt: '2026-09-25T12:00:00Z',
  },
  {
    _id: 'evt-2',
    title: '78th Gour Memorial National Science & Innovation Symposium',
    description: 'The flagship national science conference honoring the university founder, Sir Dr. Hari Singh Gour. Keynote addresses by leading scientists on advanced nanomaterials, renewable energy, and scientific self-reliance.',
    category: 'Seminar',
    organizerId: 'org-2',
    organizerName: 'Prof. R.K. Trivedi',
    organizerEmail: 'rk.trivedi@dhsgsu.edu.in',
    venue: 'Swarn Jayanti Hall (Golden Jubilee Auditorium)',
    venueId: 'venue-swarna-jayanti',
    startTime: '2026-09-30T11:30:00Z',
    endTime: '2026-09-30T15:30:00Z',
    capacity: 500,
    registrationCount: 380,
    registrationDeadline: '2026-09-29T18:00:00Z',
    tags: ['Gour Memorial', 'National Symposium', 'Sciences', 'Keynote', 'DHSGSU'],
    coverImage: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
    eligibility: 'Open to all university students, research scholars, and faculty members',
    specialInstructions: 'Formal university dress code. Seated 15 minutes before the arrival of the Vice-Chancellor.',
    departmentScope: 'Faculty of Science & Academic Council',
    createdAt: '2026-09-01T10:00:00Z',
    updatedAt: '2026-09-28T09:00:00Z',
  },
  {
    _id: 'evt-3',
    title: 'Bundelkhand Folk Heritage & University Youth Festival (Utsav 2026)',
    description: 'An evening celebrating Bundelkhand folk dance (Rai, Badhai), classical ragas, theatrical drama, and instrumental music performed by university cultural troupes across all departments.',
    category: 'Cultural',
    organizerId: 'org-1',
    organizerName: 'Dr. Alok Sahay',
    organizerEmail: 'alok.sahay@dhsgsu.edu.in',
    venue: 'Abhimanch Sabhagar (University Auditorium)',
    venueId: 'venue-abhimanch',
    startTime: '2026-10-02T17:00:00Z',
    endTime: '2026-10-02T21:00:00Z',
    capacity: 400,
    registrationCount: 290,
    registrationDeadline: '2026-10-01T23:59:00Z',
    tags: ['Cultural', 'Bundelkhand', 'Music', 'Youth Festival', 'Dance'],
    coverImage: 'https://images.unsplash.com/photo-1469488865564-c2de10f69f96?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
    eligibility: 'All students with valid DHSGSU identity card',
    specialInstructions: 'Digital event pass must be shown at the Abhimanch Sabhagar entrance.',
    departmentScope: 'University Cultural Affairs Council',
    createdAt: '2026-09-15T11:00:00Z',
    updatedAt: '2026-09-27T16:00:00Z',
  },
  {
    _id: 'evt-4',
    title: 'All-Madhya Pradesh Inter-University Hackathon: Smart Campus & AgriTech',
    description: '36-hour non-stop hackathon hosted at Jawaharlal Nehru Central Library Complex. Teams engineer functional software and IoT solutions for rural agriculture, smart energy, and digital campus services.',
    category: 'Coding',
    organizerId: 'org-1',
    organizerName: 'Dr. Alok Sahay',
    organizerEmail: 'alok.sahay@dhsgsu.edu.in',
    venue: 'Jawaharlal Nehru Central Library',
    venueId: 'venue-central-library',
    startTime: '2026-10-05T09:00:00Z',
    endTime: '2026-10-06T21:00:00Z',
    capacity: 100,
    registrationCount: 78,
    registrationDeadline: '2026-10-03T18:00:00Z',
    tags: ['Hackathon', 'Coding', 'AgriTech', 'Smart Campus', 'DHSGSU'],
    coverImage: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
    eligibility: 'Teams of 2 to 4 enrolled university students',
    specialInstructions: 'Bring extensions and personal laptops. Valid university ID card mandatory.',
    departmentScope: 'Department of Computer Science & Applications (DCSA)',
    createdAt: '2026-09-12T09:30:00Z',
    updatedAt: '2026-09-26T14:20:00Z',
  },
  {
    _id: 'evt-5',
    title: 'Inter-Departmental Cricket Championship & Athletic Trials',
    description: 'Annual inter-departmental sports tournament held at the University Sports Ground & Stadium on Patharia Hills. Selection trials for West Zone Inter-University tournaments across track, field, and cricket.',
    category: 'Sports',
    organizerId: 'org-2',
    organizerName: 'Prof. R.K. Trivedi',
    organizerEmail: 'rk.trivedi@dhsgsu.edu.in',
    venue: 'University Sports Ground & Stadium',
    venueId: 'venue-stadium',
    startTime: '2026-10-08T08:00:00Z',
    endTime: '2026-10-10T18:00:00Z',
    capacity: 600,
    registrationCount: 310,
    registrationDeadline: '2026-10-06T20:00:00Z',
    tags: ['Cricket', 'Athletics', 'Sports', 'University Stadium', 'Trials'],
    coverImage: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
    eligibility: 'Open to registered student athletes representing departmental teams',
    specialInstructions: 'Athletic wear and spiked shoes mandatory. Medical fitness clearance required.',
    departmentScope: 'Directorate of Physical Education & Sports',
    createdAt: '2026-09-18T14:00:00Z',
    updatedAt: '2026-09-28T11:00:00Z',
  },
  {
    _id: 'evt-6',
    title: 'Campus Placement & Corporate Readiness Conclave 2026',
    description: 'Central training and placement orientation featuring industry leaders and central PSU representatives. Resume clinics, mock technical interviews, and aptitude orientation.',
    category: 'Placement',
    organizerId: 'org-1',
    organizerName: 'Dr. Alok Sahay',
    organizerEmail: 'alok.sahay@dhsgsu.edu.in',
    venue: 'Swarn Jayanti Hall (Golden Jubilee Auditorium)',
    venueId: 'venue-swarna-jayanti',
    startTime: '2026-10-12T09:30:00Z',
    endTime: '2026-10-12T17:00:00Z',
    capacity: 450,
    registrationCount: 420,
    registrationDeadline: '2026-10-10T23:59:00Z',
    tags: ['Placement', 'Career', 'Interviews', 'Corporate', 'Training'],
    coverImage: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
    eligibility: 'Final and Pre-Final Year students of all undergraduate and postgraduate programs',
    specialInstructions: 'Carry 5 copies of your verified university resume and passport photographs in formal attire.',
    departmentScope: 'Central Placement Cell, DHSGSU',
    createdAt: '2026-09-14T10:00:00Z',
    updatedAt: '2026-09-29T10:30:00Z',
  },
  {
    _id: 'evt-7',
    title: 'Hands-on Workshop: Drone Mapping & Remote Sensing in Bundelkhand',
    description: 'Practical training on geospatial survey drones, multispectral imaging, and GIS mapping for environmental monitoring across the Vindhyan and Patharia hill terrain.',
    category: 'Technology',
    organizerId: 'org-2',
    organizerName: 'Prof. R.K. Trivedi',
    organizerEmail: 'rk.trivedi@dhsgsu.edu.in',
    venue: 'Department of General & Applied Geography',
    venueId: 'venue-geography-dept',
    startTime: '2026-10-15T10:00:00Z',
    endTime: '2026-10-15T15:30:00Z',
    capacity: 80,
    registrationCount: 65,
    registrationDeadline: '2026-10-13T20:00:00Z',
    tags: ['Drones', 'GIS', 'Remote Sensing', 'Technology', 'Geography'],
    coverImage: 'https://images.unsplash.com/photo-1527977966376-1c8408f9f108?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
    eligibility: 'Students of Science, Geography, Geology, and Engineering faculties',
    specialInstructions: 'Field flying demonstration will take place adjacent to the Department of General & Applied Geography.',
    departmentScope: 'Department of General & Applied Geography',
    createdAt: '2026-09-20T12:00:00Z',
    updatedAt: '2026-09-28T14:00:00Z',
  },
  {
    _id: 'evt-8',
    title: 'Student Venture Pitch & Seed Grant Showcase',
    description: 'Students present early-stage tech, social, and commercial startups before academic and industry mentors.',
    category: 'Entrepreneurship',
    organizerId: 'org-1',
    organizerName: 'Dr. Alok Sahay',
    organizerEmail: 'alok.sahay@dhsgsu.edu.in',
    venue: 'Jawaharlal Nehru Central Library',
    venueId: 'venue-central-library',
    startTime: '2026-10-18T10:00:00Z',
    endTime: '2026-10-18T16:00:00Z',
    capacity: 100,
    registrationCount: 52,
    registrationDeadline: '2026-10-16T18:00:00Z',
    tags: ['Startup', 'Pitch', 'Grants', 'Incubation', 'Entrepreneurship'],
    coverImage: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
    eligibility: 'Any enrolled student or multidisciplinary team with an innovative pitch deck',
    specialInstructions: 'Pitches limited strictly to 7 minutes followed by 5 minutes Q&A.',
    departmentScope: 'Institution Innovation Council, DHSGSU',
    createdAt: '2026-09-21T09:00:00Z',
    updatedAt: '2026-09-29T11:00:00Z',
  },
  {
    _id: 'evt-9',
    title: 'National Moot Court Competition: Constitutional Law in the Digital Age',
    description: 'National moot court competition focusing on constitutional privacy rights, surveillance regulation, and fundamental liberties in modern digital societies.',
    category: 'Competition',
    organizerId: 'org-2',
    organizerName: 'Prof. R.K. Trivedi',
    organizerEmail: 'rk.trivedi@dhsgsu.edu.in',
    venue: 'Department of Law',
    venueId: 'venue-law-hall',
    startTime: '2026-10-22T09:00:00Z',
    endTime: '2026-10-23T18:00:00Z',
    capacity: 120,
    registrationCount: 94,
    registrationDeadline: '2026-10-19T23:59:00Z',
    tags: ['Moot Court', 'Law', 'Constitution', 'Competition', 'DHSGSU'],
    coverImage: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
    eligibility: 'LL.B and B.A. LL.B student teams',
    specialInstructions: 'Advocate robes mandatory for oral arguments. Memorial submission due 48 hours prior.',
    departmentScope: 'Department of Law',
    createdAt: '2026-09-22T10:00:00Z',
    updatedAt: '2026-09-29T13:00:00Z',
  },
  {
    _id: 'evt-10',
    title: 'University Astronomy Night: Planetary Observation from Patharia Hills',
    description: 'Evening sky observation of Jupiter, Saturn’s rings, and deep-sky nebulae from the clear ridge of Patharia Hills.',
    category: 'Club',
    organizerId: 'org-1',
    organizerName: 'Dr. Alok Sahay',
    organizerEmail: 'alok.sahay@dhsgsu.edu.in',
    venue: 'Department of General & Applied Geography',
    venueId: 'venue-geography-dept',
    startTime: '2026-10-25T19:00:00Z',
    endTime: '2026-10-25T22:30:00Z',
    capacity: 150,
    registrationCount: 110,
    registrationDeadline: '2026-10-24T18:00:00Z',
    tags: ['Astronomy', 'Telescope', 'Night Sky', 'Club', 'Patharia Hills'],
    coverImage: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
    eligibility: 'Open to all students, university families, and stargazing enthusiasts',
    specialInstructions: 'Warm clothing recommended for evening winds on Patharia Hills.',
    departmentScope: 'School of Mathematical & Physical Sciences',
    createdAt: '2026-09-23T11:00:00Z',
    updatedAt: '2026-09-29T15:00:00Z',
  },
  {
    _id: 'evt-11',
    title: 'Human-Centered Design & Interactive Systems Workshop',
    description: 'A 2-day hands-on studio on information architecture, micro-interactions, and accessibility standards for modern campus digital tools. Led by visiting design researchers.',
    category: 'Academic',
    organizerId: 'org-1',
    organizerName: 'Dr. Alok Sahay',
    organizerEmail: 'alok.sahay@dhsgsu.edu.in',
    venue: 'Department of Computer Science & Applications (DCSA)',
    venueId: 'venue-dcsa-lab',
    startTime: '2026-10-28T10:00:00Z',
    endTime: '2026-10-29T16:00:00Z',
    capacity: 45,
    registrationCount: 38,
    registrationDeadline: '2026-10-26T20:00:00Z',
    tags: ['Design', 'UI/UX', 'Accessibility', 'Academic', 'DCSA'],
    coverImage: 'https://images.unsplash.com/photo-1581291518655-9523c932edcf?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
    eligibility: 'All students interested in software interface engineering and ergonomics',
    specialInstructions: 'Sketchbooks and digital wireframing tools will be supplied.',
    departmentScope: 'Department of Computer Science & Applications',
    createdAt: '2026-09-24T14:00:00Z',
    updatedAt: '2026-09-29T16:00:00Z',
  },
  {
    _id: 'evt-12',
    title: 'Annual Hindi & Bundeli Sahitya Sabha: Heritage Poetry and Dialogue',
    description: 'Writers and student poets convene at Aacharya Shankar Bhawan to celebrate the literary tradition of Bundelkhand, featuring poetry recitations and panel discussions on regional storytelling.',
    category: 'Other',
    organizerId: 'org-2',
    organizerName: 'Prof. R.K. Trivedi',
    organizerEmail: 'rk.trivedi@dhsgsu.edu.in',
    venue: 'Aacharya Shankar Bhawan',
    venueId: 'acharya-shankar-bhawan',
    startTime: '2026-11-01T14:00:00Z',
    endTime: '2026-11-01T18:00:00Z',
    capacity: 150,
    registrationCount: 88,
    registrationDeadline: '2026-10-30T18:00:00Z',
    tags: ['Literature', 'Hindi', 'Bundelkhand', 'Poetry', 'Heritage'],
    coverImage: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80',
    status: 'PUBLISHED',
    eligibility: 'Open to all university community members',
    specialInstructions: 'Students wishing to recite original poetry must register at the podium by 1:30 PM.',
    departmentScope: 'School of Languages',
    createdAt: '2026-09-25T10:00:00Z',
    updatedAt: '2026-09-29T17:00:00Z',
  },
  {
    _id: 'evt-13',
    title: 'National Symposium on Quantum Cryptography & Post-Quantum Security',
    description: 'Proposed 1-day research seminar inviting cryptographers and computer scientists to discuss lattice-based cryptography and secure digital infrastructure.',
    category: 'Seminar',
    organizerId: 'org-1',
    organizerName: 'Dr. Alok Sahay',
    organizerEmail: 'alok.sahay@dhsgsu.edu.in',
    venue: 'Administrative Building (Gour Samiti Kaksh)',
    venueId: 'venue-gour-bhavan',
    startTime: '2026-11-05T10:30:00Z',
    endTime: '2026-11-05T16:30:00Z',
    capacity: 150,
    registrationCount: 0,
    registrationDeadline: '2026-11-03T18:00:00Z',
    tags: ['Cryptography', 'Security', 'Seminar', 'DCSA', 'Research'],
    coverImage: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=800&q=80',
    status: 'PENDING_REVIEW',
    eligibility: 'Postgraduate students, research scholars, and faculty members',
    specialInstructions: 'Submitted for DSW administrative review.',
    departmentScope: 'Department of Computer Science & Applications (DCSA)',
    createdAt: '2026-09-29T18:00:00Z',
    updatedAt: '2026-09-29T18:00:00Z',
  },
  {
    _id: 'evt-14',
    title: 'Embedded Rust & RISC-V Microcontroller Lab Bootcamp',
    description: 'Hands-on laboratory workshop introducing memory-safe embedded systems programming on RISC-V development boards.',
    category: 'Workshop',
    organizerId: 'org-1',
    organizerName: 'Dr. Alok Sahay',
    organizerEmail: 'alok.sahay@dhsgsu.edu.in',
    venue: 'Department of Computer Science & Applications (DCSA)',
    venueId: 'venue-dcsa-lab',
    startTime: '2026-11-12T10:00:00Z',
    endTime: '2026-11-12T16:00:00Z',
    capacity: 60,
    registrationCount: 0,
    registrationDeadline: '2026-11-10T23:59:00Z',
    tags: ['Rust', 'Embedded', 'RISC-V', 'Workshop', 'Hardware'],
    coverImage: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=800&q=80',
    status: 'DRAFT',
    eligibility: 'B.Tech and MCA students',
    specialInstructions: 'Draft proposal being prepared by faculty convener.',
    departmentScope: 'Department of Computer Science & Applications (DCSA)',
    createdAt: '2026-09-30T08:00:00Z',
    updatedAt: '2026-09-30T08:00:00Z',
  }
];

export const INITIAL_REGISTRATIONS: Registration[] = [
  {
    _id: 'reg-1',
    eventId: 'evt-1',
    userId: 'student-1',
    userName: 'Amit Sharma',
    userRollNumber: 'Y23141042',
    userDepartment: 'Department of Computer Science & Applications',
    userEmail: 'amit.sharma@dhsgsu.edu.in',
    status: 'CONFIRMED',
    registeredAt: '2026-09-20T14:30:00Z',
    qrToken: 'PARISAR-PASS-DL-CS042',
    checkedInAt: null,
  },
  {
    _id: 'reg-2',
    eventId: 'evt-2',
    userId: 'student-1',
    userName: 'Amit Sharma',
    userRollNumber: 'Y23141042',
    userDepartment: 'Department of Computer Science & Applications',
    userEmail: 'amit.sharma@dhsgsu.edu.in',
    status: 'CONFIRMED',
    registeredAt: '2026-09-22T09:15:00Z',
    qrToken: 'PARISAR-PASS-GM-CS042',
    checkedInAt: null,
  },
  {
    _id: 'reg-3',
    eventId: 'evt-3',
    userId: 'student-2',
    userName: 'Priya Patel',
    userRollNumber: 'Y23122018',
    userDepartment: 'Department of Electronics & Communication',
    userEmail: 'priya.patel@dhsgsu.edu.in',
    status: 'CONFIRMED',
    registeredAt: '2026-09-21T16:00:00Z',
    qrToken: 'PARISAR-PASS-UT-EC118',
    checkedInAt: '2026-09-30T09:12:00Z',
  },
  {
    _id: 'reg-4',
    eventId: 'evt-1',
    userId: 'student-3',
    userName: 'Rohan Mehra',
    userRollNumber: 'Y23141088',
    userDepartment: 'Department of Computer Science & Applications',
    userEmail: 'rohan.mehra@dhsgsu.edu.in',
    status: 'CONFIRMED',
    registeredAt: '2026-09-20T15:00:00Z',
    qrToken: 'PARISAR-PASS-DL-CS088',
    checkedInAt: '2026-09-30T08:45:00Z',
  }
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    _id: 'att-1',
    eventId: 'evt-1',
    registrationId: 'reg-4',
    userId: 'student-3',
    userName: 'Rohan Mehra',
    userRollNumber: 'Y23141088',
    userDepartment: 'Department of Computer Science & Applications',
    checkedInAt: '2026-09-30T08:45:00Z',
    checkedInBy: 'org-1',
    method: 'qr',
  },
  {
    _id: 'att-2',
    eventId: 'evt-3',
    registrationId: 'reg-3',
    userId: 'student-2',
    userName: 'Priya Patel',
    userRollNumber: 'Y23122018',
    userDepartment: 'Department of Electronics & Communication',
    checkedInAt: '2026-09-30T09:12:00Z',
    checkedInBy: 'org-1',
    method: 'qr',
  }
];

export const INITIAL_CERTIFICATES: Certificate[] = [
  {
    _id: 'cert-1',
    eventId: 'evt-past-1',
    eventTitle: 'National Workshop on High-Performance Distributed Computing',
    userId: 'student-1',
    userName: 'Amit Sharma',
    userRollNumber: 'Y23141042',
    department: 'Department of Computer Science & Applications',
    certificateUrl: '/certificates/cert-hp-dc-042.pdf',
    verificationCode: 'DHSGSU-CERT-2026-CS8841',
    issuedAt: '2026-08-28T16:00:00Z',
    certificateType: 'EXCELLENCE',
    issueAuthorizedBy: 'Dr. Alok Sahay, Faculty Convener',
    academicAuthority: "Office of the Dean of Students' Welfare (DSW), DHSGSU",
  },
  {
    _id: 'cert-2',
    eventId: 'evt-past-2',
    eventTitle: 'Inter-University Bundelkhand Science Hackathon 2025',
    userId: 'student-1',
    userName: 'Amit Sharma',
    userRollNumber: 'Y23141042',
    department: 'Department of Computer Science & Applications',
    certificateUrl: '/certificates/cert-hack-042.pdf',
    verificationCode: 'DHSGSU-CERT-2025-HK3319',
    issuedAt: '2025-11-15T18:00:00Z',
    certificateType: 'MERIT',
    issueAuthorizedBy: 'Prof. R.K. Trivedi, Organizing Secretary',
    academicAuthority: "Office of the Dean of Students' Welfare (DSW), DHSGSU",
  }
];

export const INITIAL_NOTIFICATIONS: CampusNotification[] = [
  {
    _id: 'notif-1',
    userId: 'student-1',
    eventId: 'evt-1',
    type: 'REGISTRATION_CONFIRMED',
    title: 'Registration Confirmed: Deep Learning Workshop',
    message: 'Your seat at the Department of Computer Science & Applications (DCSA) is confirmed. Your PARISAR digital pass is ready for door check-in.',
    read: false,
    createdAt: '2026-09-29T14:30:00Z',
  },
  {
    _id: 'notif-2',
    userId: 'student-1',
    eventId: 'evt-1',
    type: 'VENUE_CHANGED',
    title: 'Laboratory Preparation Notice',
    message: 'Please ensure PyTorch and Python 3.11 are installed on your personal laptops before arriving at the Department of Computer Science & Applications (DCSA).',
    read: false,
    createdAt: '2026-09-30T07:15:00Z',
  },
  {
    _id: 'notif-3',
    userId: 'student-1',
    eventId: 'evt-2',
    type: 'EVENT_REMINDER',
    title: 'Event Today: 78th Gour Memorial Symposium',
    message: 'Starting at 11:30 AM in Swarn Jayanti Hall (Golden Jubilee Auditorium). Please arrive 15 minutes before the academic procession begins.',
    read: true,
    createdAt: '2026-09-30T06:00:00Z',
  }
];

export const INITIAL_ACHIEVEMENTS: AchievementBadge[] = [
  {
    id: 'ach-1',
    name: 'DHSGSU Campus Explorer',
    description: 'Participated in university events across 3 distinct academic faculties on Patharia Hills.',
    iconName: 'Compass',
    category: 'Exploration',
    unlockedAt: '2026-08-28T16:00:00Z',
    progress: 3,
    total: 3,
  },
  {
    id: 'ach-2',
    name: 'Advanced Computing Scholar',
    description: 'Successfully completed 30+ verified lab workshop hours organized by DCSA.',
    iconName: 'Cpu',
    category: 'Workshops',
    unlockedAt: '2026-09-15T12:00:00Z',
    progress: 30,
    total: 30,
  },
  {
    id: 'ach-3',
    name: 'Gour Memorial Honoree',
    description: 'Attended the prestigious annual university founder commemoration symposium.',
    iconName: 'Award',
    category: 'Academic',
    progress: 2,
    total: 3,
  },
  {
    id: 'ach-4',
    name: 'Hackathon Contender',
    description: 'Engineered a working software prototype during an inter-university coding competition.',
    iconName: 'Zap',
    category: 'Coding',
    unlockedAt: '2025-11-15T18:00:00Z',
    progress: 1,
    total: 1,
  }
];

export const PASSPORT_ACHIEVEMENTS = INITIAL_ACHIEVEMENTS;

export const INITIAL_FEEDBACK: EventFeedback[] = [
  {
    _id: 'fb-1',
    eventId: 'evt-past-1',
    userId: 'student-1',
    userName: 'Amit Sharma',
    rating: 5,
    comment: 'Exceptional hands-on training in the DCSA lab. The practical GPU pipelines were immediately applicable.',
    createdAt: '2026-08-29T10:00:00Z',
  },
  {
    _id: 'fb-2',
    eventId: 'evt-past-1',
    userId: 'student-2',
    userName: 'Priya Patel',
    rating: 5,
    comment: 'Clear explanations and excellent faculty mentoring from Dr. Alok Sahay.',
    createdAt: '2026-08-29T11:30:00Z',
  }
];
