plugins {
    id 'com.android.application'
}

android {
    namespace 'in.edu.dhsgsu.parisar'
    compileSdk 34

    defaultConfig {
        applicationId "in.edu.dhsgsu.parisar"
        minSdk 26
        targetSdk 34
        versionCode 3
        versionName "2.1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            if (file('release.keystore').exists()) {
                storeFile file('release.keystore')
                storePassword 'parisar2026'
                keyAlias 'parisar'
                keyPassword 'parisar2026'
            }
        }
    }

    buildTypes {
        release {
            if (file('release.keystore').exists()) {
                signingConfig signingConfigs.release
            } else {
                signingConfig signingConfigs.debug
            }
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.webkit:webkit:1.10.0'
}
